Repository scverse/scvi-tools, pull requests merged in 2022-10, with the labels that each got.

#1710 Update CI workflow to separate static code checking from pytest.
  .github/workflows/test.yml
Labels: enhancement

#1719 Allow PyTorch Lightning 1.6
  pyproject.toml
Labels: dependencies

#1696 Replace custom `attrdict` with `ml_collections` implementation.
  docs/conf.py
  pyproject.toml
  scvi/data/_manager.py
  scvi/data/_utils.py
  scvi/data/fields/_protein.py
  scvi/model/_totalvi.py
  scvi/module/_totalvae.py
  scvi/utils/_attrdict.py
  tests/models/test_models.py
  tests/models/test_mudata_models.py
  tests/models/test_scarches.py
  tests/utils/test_attrdict.py
Labels: enhancement, dependencies

#1737 Fix `n_proteins` usage in MULTIVI
  scvi/model/_multivi.py
  tests/models/test_models.py
Labels: on-merge: backport to 0.18.x

#1739 Backport PR #1737 on branch 0.18.x (Fix `n_proteins` usage in MULTIVI)
  scvi/model/_multivi.py
  tests/models/test_models.py
Labels: on-merge: backport to 0.18.x

#1741 Fix unused param
  scvi/model/_multivi.py
Labels: on-merge: backport to 0.18.x

#1742 Backport PR #1741 on branch 0.18.x (Fix unused param)
  scvi/model/_multivi.py
Labels: on-merge: backport to 0.18.x

#1777 Backport PR #1776 on branch 0.19.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 0.19.x
