Repository scverse/scvi-tools, pull requests merged in 2022-09, with the labels that each got.

#1660 Fix typo in the logic for throwing exception in the VAE module
  scvi/module/_vae.py
Labels: on-merge: backport to 0.17.x

#1667 Update publication links
  README.md
Labels: on-merge: backport to 0.17.x

#1668 Backport PR #1667 on branch 0.17.x (Update publication links)
  README.md
Labels: on-merge: backport to 0.17.x

#1671 change to super().__init__()
  scvi/external/gimvi/_model.py
  scvi/external/stereoscope/_model.py
  scvi/model/_autozi.py
  scvi/model/_condscvi.py
  scvi/model/_destvi.py
  scvi/model/_linear_scvi.py
  scvi/model/_peakvi.py
  scvi/model/_scanvi.py
  scvi/model/_scvi.py
  scvi/model/_totalvi.py
  scvi/nn/_base_components.py
  scvi/train/_trainingplans.py
Labels: on-merge: backport to 0.17.x

#1676 Backport PR #1671 on branch 0.17.x (change to super().__init__())
  scvi/external/gimvi/_model.py
  scvi/external/stereoscope/_model.py
  scvi/model/_autozi.py
  scvi/model/_condscvi.py
  scvi/model/_destvi.py
  scvi/model/_linear_scvi.py
  scvi/model/_peakvi.py
  scvi/model/_scanvi.py
  scvi/model/_scvi.py
  scvi/model/_totalvi.py
  scvi/nn/_base_components.py
  scvi/train/_trainingplans.py
Labels: on-merge: backport to 0.17.x

#1678 Doc touchups: linkcode, hoverxref, grid
  docs/conf.py
  docs/index.md
  pyproject.toml
Labels: on-merge: backport to 0.17.x

#1679 Backport PR #1678 on branch 0.17.x (Doc touchups: linkcode, hoverxref, grid)
  docs/conf.py
  docs/index.md
  pyproject.toml
Labels: on-merge: backport to 0.17.x

#1618 Likelihood params bugfix
  scvi/model/base/_rnamixin.py
  tests/models/test_models.py
Labels: on-merge: backport to 0.17.x

#1622 Update to PyTorch Lightning 1.7
  pyproject.toml
  scvi/dataloaders/_data_splitting.py
  scvi/external/gimvi/_model.py
  scvi/model/_utils.py
  scvi/model/base/_archesmixin.py
  scvi/model/base/_base_model.py
  scvi/model/base/_pyromixin.py
  scvi/module/base/_base_module.py
  scvi/module/base/_jax_module_wrapper.py
  scvi/train/_logger.py
  scvi/train/_trainrunner.py
Labels: on-merge: backport to 0.17.x

#1680 Backport PR #1618 on branch 0.17.x (Likelihood params bugfix)
  scvi/model/base/_rnamixin.py
  tests/models/test_models.py
Labels: on-merge: backport to 0.17.x

#1681 Backport PR #1622 on branch 0.17.x (Update to PyTorch Lightning 1.7)
  pyproject.toml
  scvi/dataloaders/_data_splitting.py
  scvi/external/gimvi/_model.py
  scvi/model/_utils.py
  scvi/model/base/_archesmixin.py
  scvi/model/base/_base_model.py
  scvi/model/base/_pyromixin.py
  scvi/module/base/_base_module.py
  scvi/module/base/_jax_module_wrapper.py
  scvi/train/_logger.py
  scvi/train/_trainrunner.py
Labels: on-merge: backport to 0.17.x

#1686 Max epochs must be int
  scvi/external/cellassign/_model.py
  scvi/external/solo/_model.py
  scvi/model/_scanvi.py
  scvi/model/_totalvi.py
  scvi/model/base/_jaxmixin.py
  scvi/model/base/_pyromixin.py
  scvi/model/base/_training_mixin.py
  scvi/module/base/_base_module.py
  scvi/module/base/_jax_module_wrapper.py
Labels: on-merge: backport to 0.17.x

#1687 Backport PR #1686 on branch 0.17.x (Max epochs must be int)
  scvi/external/cellassign/_model.py
  scvi/external/solo/_model.py
  scvi/model/_scanvi.py
  scvi/model/_totalvi.py
  scvi/model/base/_jaxmixin.py
  scvi/model/base/_pyromixin.py
  scvi/model/base/_training_mixin.py
  scvi/module/base/_base_module.py
  scvi/module/base/_jax_module_wrapper.py
Labels: on-merge: backport to 0.17.x

#1692 bugfix old torch trying to use m1 gpu
  scvi/model/_utils.py
Labels: on-merge: backport to 0.17.x

#1665 Adapt flax to use any mutable states used by a model generically
  scvi/module/base/__init__.py
  scvi/module/base/_jax_module_wrapper.py
  scvi/train/_callbacks.py
  scvi/train/_trainingplans.py
Labels: on-merge: backport to 0.17.x

#1699 Backport PR #1665 on branch 0.17.x (Adapt flax to use any mutable states used by a model generically)
  scvi/module/base/__init__.py
  scvi/module/base/_jax_module_wrapper.py
  scvi/train/_callbacks.py
  scvi/train/_trainingplans.py
Labels: on-merge: backport to 0.17.x

#1698 Backport PR #1692 on branch 0.17.x (bugfix old torch trying to use m1 gpu)
  scvi/model/_utils.py
Labels: on-merge: backport to 0.17.x

#1700 fix jax state, bug in .pop
  scvi/train/_callbacks.py
Labels: on-merge: backport to 0.17.x

#1701 Backport PR #1700 on branch 0.17.x (fix jax state, bug in .pop)
  scvi/train/_callbacks.py
Labels: on-merge: backport to 0.17.x

#1702 Quick fix in poisson sample() function for vae
  scvi/module/_vae.py
  tests/models/test_models.py
Labels: on-merge: backport to 0.17.x

#1703 Backport PR #1702 on branch 0.17.x (Quick fix in poisson sample() function for vae)
  scvi/module/_vae.py
  tests/models/test_models.py
Labels: on-merge: backport to 0.17.x

#1694 Add release notes for v0.17.4, bump version.
  docs/release_notes/index.md
  docs/release_notes/v0.17.4.md
  pyproject.toml
Labels: on-merge: backport to 0.17.x

#1704 Backport PR #1694 on branch 0.17.x (Add release notes for v0.17.4, bump version.)
  docs/release_notes/index.md
  docs/release_notes/v0.17.4.md
  pyproject.toml
Labels: on-merge: backport to 0.17.x

#1695 Faster inference in PyTorch with `torch.inference_mode`.
  scvi/data/_preprocessing.py
  scvi/distributions/_negative_binomial.py
  scvi/external/cellassign/_model.py
  scvi/external/cellassign/_module.py
  scvi/external/gimvi/_model.py
  scvi/external/solo/_model.py
  scvi/external/stereoscope/_module.py
  scvi/model/_autozi.py
  scvi/model/_condscvi.py
  scvi/model/_multivi.py
  scvi/model/_peakvi.py
  scvi/model/_totalvi.py
  scvi/model/base/_archesmixin.py
  scvi/model/base/_differential.py
  scvi/model/base/_pyromixin.py
  scvi/model/base/_rnamixin.py
  scvi/model/base/_vaemixin.py
  scvi/module/_amortizedlda.py
  scvi/module/_mrdeconv.py
  scvi/module/_totalvae.py
  scvi/module/_vae.py
  scvi/module/_vaec.py
  scvi/train/_trainingplans.py
Labels: enhancement

#1709 Fix links for breast cancer and mouse ob.
  scvi/data/_built_in_data/_csv.py
Labels: bug
