Repository scverse/scvi-tools, pull requests merged in 2024-12, with the labels that each got.

#3068 Backport PR #3067 on branch 1.2.x (fix: CUDA Minified Tests following refactoring)
  tests/model/test_models_with_minified_data.py
Labels: cuda tests, on-merge: backport to 1.2.x

#3069 release: Updates for scvi-tools v1.2.1
  CHANGELOG.md
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#3070 release: backport Updates for scvi-tools v1.2.1
  CHANGELOG.md
  pyproject.toml
Labels: releases

#3071 docs: Update methylvi tutorial link
  docs/tutorials/index.md
  docs/tutorials/index_scbs.md
  docs/user_guide/models/methylvi.md
Labels: on-merge: backport to 1.2.x

#3072 Backport PR #3071 on branch 1.2.x (docs: Update methylvi tutorial link)
  docs/tutorials/index.md
  docs/tutorials/index_scbs.md
  docs/user_guide/models/methylvi.md
Labels: on-merge: backport to 1.2.x

#3075 Docs: Update YosefLab link
  docs/index.md
Labels: on-merge: backport to 1.2.x

#3076 Backport PR #3075 on branch 1.2.x (Docs: Update YosefLab link)
  docs/index.md
Labels: on-merge: backport to 1.2.x

#3061 feat: Support for minification in totalVI
  CHANGELOG.md
  src/scvi/data/_utils.py
  src/scvi/model/_scanvi.py
  src/scvi/model/_scvi.py
  src/scvi/model/_totalvi.py
  src/scvi/model/_utils.py
  src/scvi/model/base/__init__.py
  src/scvi/model/base/_base_model.py
  src/scvi/model/base/_de_core.py
  src/scvi/model/utils/__init__.py
  src/scvi/model/utils/_minification.py
  src/scvi/module/_totalvae.py
  tests/model/test_models_with_mudata_minified_data.py
Labels: cuda tests, on-merge: backport to 1.2.x

#3077 Backport PR #3061 on branch 1.2.x (feat: Support for minification in totalVI)
  CHANGELOG.md
  src/scvi/data/_utils.py
  src/scvi/model/_scanvi.py
  src/scvi/model/_scvi.py
  src/scvi/model/_totalvi.py
  src/scvi/model/_utils.py
  src/scvi/model/base/__init__.py
  src/scvi/model/base/_base_model.py
  src/scvi/model/base/_de_core.py
  src/scvi/model/utils/__init__.py
  src/scvi/model/utils/_minification.py
  src/scvi/module/_totalvae.py
  tests/model/test_models_with_mudata_minified_data.py
Labels: cuda tests, on-merge: backport to 1.2.x

#3080 build: Fix changelog and update cuda dependecy list
  CHANGELOG.md
  pyproject.toml
  src/scvi/external/methylvi/_model.py
Labels: releases, on-merge: backport to 1.2.x

#3053 Fix: distributed sampler for multi GPU
  .github/workflows/test_linux_multigpu.yml
  CHANGELOG.md
  src/scvi/dataloaders/_concat_dataloader.py
  tests/conftest.py
  tests/dataloaders/test_dataloaders.py
  tests/dataloaders/test_datasplitter.py
  tests/model/test_multigpu.py
Labels: on-merge: backport to 1.3.x, multiGPU tests

#3087 Backport PR #3086 on branch 1.2.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.2.x

#3085 misc: Address AnnData >= 0.11 deprecation warnings
  CHANGELOG.md
  pyproject.toml
  src/scvi/data/__init__.py
  src/scvi/data/_anntorchdataset.py
  src/scvi/data/_built_in_data/_csv.py
  src/scvi/data/_utils.py
Labels: on-merge: backport to 1.2.x

#3096 Backport PR #3095 on branch 1.2.x (fix: Explicity use weights_only=False in torch.load functions)
  src/scvi/external/gimvi/_utils.py
  src/scvi/model/base/_save_load.py
  tests/model/test_pyro.py
  tests/nn/test_embedding.py
Labels: on-merge: backport to 1.2.x

#3099 Backport PR #3098 on branch 1.2.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.2.x

#3038 feat: Mudata support for MultiVI
  CHANGELOG.md
  pyproject.toml
  src/scvi/_constants.py
  src/scvi/data/fields/_arraylike_field.py
  src/scvi/model/_multivi.py
  src/scvi/module/_multivae.py
  tests/model/test_multivi.py
Labels: multivi, on-merge: backport to 1.2.x

#2842 feat: support numpy 2.0
  CHANGELOG.md
  docs/api/user.md
  docs/conf.py
  pyproject.toml
  src/scvi/data/_built_in_data/_loom.py
  src/scvi/data/_built_in_data/_smfish.py
  src/scvi/model/utils/__init__.py
  src/scvi/model/utils/_mde.py
  tests/data/test_built_in_data.py
  tests/model/test_scvi.py
  tests/test_data/Cortex.loom
  tests/test_data/fc-dropseq.loom
  tests/test_data/mpfc-starmap.loom
  tests/test_data/osmFISH_SScortex_mouse_all_cell.loom
  tests/test_data/retina.loom
  tests/test_data/simulation/simulation_1.loom
  tests/test_data/simulation/simulation_2.loom
  tests/test_data/simulation/simulation_3.loom
Labels: on-merge: backport to 1.2.x

#3091 Add Decipher post-training methods
  CHANGELOG.md
  src/scvi/external/decipher/_model.py
  src/scvi/external/decipher/utils/__init__.py
  src/scvi/external/decipher/utils/_rotate.py
  src/scvi/external/decipher/utils/_trajectory.py
  tests/external/decipher/test_decipher.py
Labels: on-merge: backport to 1.3.x

#3107 Backport PR #3038 on branch 1.2.x (feat: Mudata support for MultiVI)
  CHANGELOG.md
  pyproject.toml
  src/scvi/_constants.py
  src/scvi/data/fields/_arraylike_field.py
  src/scvi/model/_multivi.py
  src/scvi/module/_multivae.py
  tests/model/test_multivi.py
Labels: multivi, on-merge: backport to 1.2.x

#3111 test: Fix slow tests
  pyproject.toml
  src/scvi/data/_preprocessing.py
  src/scvi/utils/_docstrings.py
  tests/data/test_anndata.py
  tests/model/test_differential.py
  tests/model/test_multivi.py
  tests/model/test_scvi.py
  tests/model/test_totalvi.py
Labels: on-merge: backport to 1.2.x

#3112 Backport PR #3111 on branch 1.2.x (test: Fix slow tests)
  pyproject.toml
  src/scvi/data/_preprocessing.py
  src/scvi/utils/_docstrings.py
  tests/data/test_anndata.py
  tests/model/test_differential.py
  tests/model/test_multivi.py
  tests/model/test_scvi.py
  tests/model/test_totalvi.py
Labels: on-merge: backport to 1.2.x

#3114 Backport PR #3113 on branch 1.2.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.2.x, on-merge: backport to 1.3.x

#3078 feat: Change template for HuggingFace.
  CHANGELOG.md
  pyproject.toml
  src/scvi/criticism/__init__.py
  src/scvi/criticism/_create_criticism_report.py
  src/scvi/criticism/_ppc.py
  src/scvi/data/_manager.py
  src/scvi/hub/_constants.py
  src/scvi/hub/_metadata.py
  src/scvi/hub/_model.py
  src/scvi/hub/_template.py
  src/scvi/model/_totalvi.py
  src/scvi/module/_vaec.py
  tests/hub/test_hub_model.py
  tests/model/test_models_with_mudata_minified_data.py
  tests/model/test_totalvi.py
Labels: hub, cuda tests, private tests, on-merge: backport to 1.2.x

#3110 bug: CUDA fix in decipher
  src/scvi/external/decipher/_model.py
Labels: cuda tests, on-merge: backport to 1.3.x

#3115 ci: manual backport scvi hub 1.2.x
  CHANGELOG.md
  pyproject.toml
  src/scvi/criticism/__init__.py
  src/scvi/criticism/_create_criticism_report.py
  src/scvi/criticism/_ppc.py
  src/scvi/data/_manager.py
  src/scvi/external/decipher/_model.py
  src/scvi/external/decipher/utils/__init__.py
  src/scvi/external/decipher/utils/_rotate.py
  src/scvi/external/decipher/utils/_trajectory.py
  src/scvi/hub/_constants.py
  src/scvi/hub/_metadata.py
  src/scvi/hub/_model.py
  src/scvi/hub/_template.py
  src/scvi/model/_totalvi.py
  src/scvi/module/_vaec.py
  tests/external/decipher/test_decipher.py
  tests/hub/test_hub_model.py
  tests/model/test_models_with_mudata_minified_data.py
  tests/model/test_totalvi.py
Labels: on-merge: backport to 1.2.x
