Repository scverse/scvi-tools, pull requests merged in 2024-09, with the labels that each got.

#2961 Remove dependency anndata 0.10.8
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#2936 feat(train) Add support for categorial covariates in scArches
  CHANGELOG.md
  src/scvi/model/base/_archesmixin.py
  tests/model/test_scanvi.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.2.x, P1

#2962 Backport PR #2961 on branch 1.2.x (Remove dependency anndata 0.10.8)
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#2964 Backport PR #2936 on branch 1.2.x (feat(train) Add support for categorial covariates in scArches)
  CHANGELOG.md
  src/scvi/model/base/_archesmixin.py
  tests/model/test_scanvi.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.2.x, P1

#2959 docs: fix progress bar interactive style in RTD
  src/scvi/utils/_track.py
Labels: enhancement

#2982 test: Fix hugging face create repo test which was failing
  tests/hub/test_hub_model.py
Labels: private tests, on-merge: backport to 1.2.x

#2960 docs: Counterfactual prediction user guide
  docs/user_guide/background/counterfactual_prediction.md
  docs/user_guide/background/figures/counterfactual_cartoon.svg
Labels: on-merge: backport to 1.2.x

#2986 Backport PR #2960 on branch 1.2.x (docs: Counterfactual prediction user guide)
  docs/user_guide/background/counterfactual_prediction.md
  docs/user_guide/background/figures/counterfactual_cartoon.svg
Labels: on-merge: backport to 1.2.x

#2987 test: update the resolution test workflow
  .github/workflows/test_linux_resolution.yml
Labels: on-merge: backport to 1.2.x, resolution tests

#2988 Backport PR #2987 on branch 1.2.x (test: update the resolution test workflow)
  .github/workflows/test_linux_resolution.yml
Labels: on-merge: backport to 1.2.x, resolution tests

#2984 Backport PR #2982 on branch 1.2.x (test: Fix hugging face create repo test which was failing)
  tests/hub/test_hub_model.py
Labels: private tests, on-merge: backport to 1.2.x

#2989 Update pyproject.toml
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#2990 Backport PR #2989 on branch 1.2.x (Update pyproject.toml)
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#3000 Update pyproject.toml
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#3002 Backport PR #3000 on branch 1.2.x (Update pyproject.toml)
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#3001 Backport PR #2999 on branch 1.2.x (Fix warning for DA function in MrVI)
  src/scvi/external/mrvi/_model.py
Labels: on-merge: backport to 1.2.x
