Repository scverse/scvi-tools, pull requests merged in 2024-03, with the labels that each got.

#2584 [releases] add date for 1.1.2
  docs/release_notes/index.md
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2585 Backport PR #2584 on branch 1.2.x ([releases] add date for 1.1.2)
  docs/release_notes/index.md
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2588 remove `InvalidParameterError`
  scvi/data/_anntorchdataset.py
  scvi/model/_utils.py
  scvi/utils/__init__.py
  scvi/utils/_exceptions.py
  tests/data/test_anntorchdataset.py
Labels: on-merge: backport to 1.2.x

#2589 Backport PR #2588 on branch 1.2.x (remove `InvalidParameterError`)
  scvi/data/_anntorchdataset.py
  scvi/model/_utils.py
  scvi/utils/__init__.py
  scvi/utils/_exceptions.py
  tests/data/test_anntorchdataset.py
Labels: on-merge: backport to 1.2.x

#2594 [misc] use module constants, clean up typing and docs in `VAE`
  docs/api/developer.md
  scvi/__init__.py
  scvi/_constants.py
  scvi/model/_scvi.py
  scvi/model/base/_vaemixin.py
  scvi/module/_constants.py
  scvi/module/_vae.py
  scvi/train/__init__.py
  scvi/train/_constants.py
  scvi/train/_trainingplans.py
  tests/model/test_scvi.py
  tests/train/test_trainingplans.py
Labels: on-merge: backport to 1.2.x

#2595 Backport PR #2594 on branch 1.2.x ([misc] use module constants, clean up typing and docs in `VAE`)
  docs/api/developer.md
  scvi/__init__.py
  scvi/_constants.py
  scvi/model/_scvi.py
  scvi/model/base/_vaemixin.py
  scvi/module/_constants.py
  scvi/module/_vae.py
  scvi/train/__init__.py
  scvi/train/_constants.py
  scvi/train/_trainingplans.py
  tests/model/test_scvi.py
  tests/train/test_trainingplans.py
Labels: on-merge: backport to 1.2.x

#2600 [ci] use uv for installs in linux
  .github/workflows/test_linux.yml
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_pre.yml
  .github/workflows/test_linux_private.yml
Labels: all tests

#2603 [feat] add option to generate synthetic coords
  docs/release_notes/index.md
  scvi/data/_built_in_data/_synthetic.py
  scvi/data/_datasets.py
  tests/data/test_synthetic_iid.py
Labels: on-merge: backport to 1.2.x

#2605 [feat] add support for datamodules in autotune
  docs/release_notes/index.md
  scvi/autotune/_experiment.py
  scvi/autotune/_tune.py
  scvi/train/_trainrunner.py
  tests/autotune/test_experiment.py
  tests/autotune/test_tune.py
Labels: on-merge: backport to 1.2.x

#2606 Backport PR #2605 on branch 1.2.x ([feat] add support for datamodules in autotune)
  docs/release_notes/index.md
  scvi/autotune/_experiment.py
  scvi/autotune/_tune.py
  scvi/train/_trainrunner.py
  tests/autotune/test_experiment.py
  tests/autotune/test_tune.py
Labels: on-merge: backport to 1.2.x

#2611 feat(external): add velovi to external
  docs/api/developer.md
  docs/api/user.md
  docs/references.bib
  docs/release_notes/index.md
  pyproject.toml
  scvi/external/__init__.py
  scvi/external/velovi/__init__.py
  scvi/external/velovi/_constants.py
  scvi/external/velovi/_model.py
  scvi/external/velovi/_module.py
  scvi/external/velovi/_utils.py
  tests/external/velovi/test_velovi.py
Labels: on-merge: backport to 1.2.x

#2612 Backport PR #2611 on branch 1.2.x (feat(external): add velovi to external)
  docs/api/developer.md
  docs/api/user.md
  docs/references.bib
  docs/release_notes/index.md
  pyproject.toml
  scvi/external/__init__.py
  scvi/external/velovi/__init__.py
  scvi/external/velovi/_constants.py
  scvi/external/velovi/_model.py
  scvi/external/velovi/_module.py
  scvi/external/velovi/_utils.py
  tests/external/velovi/test_velovi.py
Labels: on-merge: backport to 1.2.x

#2615 feat(hub): add unsigned arg to hubmodel s3 pull
  docs/release_notes/index.md
  scvi/hub/_model.py
Labels: private tests, on-merge: backport to 1.2.x

#2617 Backport PR #2615 on branch 1.2.x (feat(hub): add unsigned arg to hubmodel s3 pull)
  docs/release_notes/index.md
  scvi/hub/_model.py
Labels: private tests, on-merge: backport to 1.2.x

#2608 Deprecation warning for scvi.nn._utils.one_hot, in favour of PyTorch version
  docs/release_notes/index.md
  scvi/external/cellassign/_module.py
  scvi/external/contrastivevi/_module.py
  scvi/external/gimvi/_module.py
  scvi/external/gimvi/_task.py
  scvi/module/_autozivae.py
  scvi/module/_multivae.py
  scvi/module/_totalvae.py
  scvi/module/_utils.py
  scvi/module/_vae.py
  scvi/nn/_base_components.py
  scvi/nn/_utils.py
  scvi/train/_trainingplans.py
  tests/nn/test_one_hot.py
Labels: cuda tests, on-merge: backport to 1.2.x

#2621 Backport PR #2608 on branch 1.2.x (Deprecation warning for scvi.nn._utils.one_hot, in favour of PyTorch version)
  docs/release_notes/index.md
  scvi/external/cellassign/_module.py
  scvi/external/contrastivevi/_module.py
  scvi/external/gimvi/_module.py
  scvi/external/gimvi/_task.py
  scvi/module/_autozivae.py
  scvi/module/_multivae.py
  scvi/module/_totalvae.py
  scvi/module/_utils.py
  scvi/module/_vae.py
  scvi/nn/_base_components.py
  scvi/nn/_utils.py
  scvi/train/_trainingplans.py
  tests/nn/test_one_hot.py
Labels: cuda tests, on-merge: backport to 1.2.x

#2629 chore(test): add pre batch key condscvi save
  tests/test_data/condscvi_pre_batch/model.pt
Labels: on-merge: backport to 1.2.x

#2630 Backport PR #2629 on branch 1.2.x (chore(test): add pre batch key condscvi save)
  tests/test_data/condscvi_pre_batch/model.pt
Labels: on-merge: backport to 1.2.x

#2626 feat(model): support batch key in condscvi
  docs/release_notes/index.md
  scvi/model/_condscvi.py
  scvi/module/_vaec.py
  tests/model/test_condscvi.py
Labels: on-merge: backport to 1.2.x

#2633 Backport PR #2626 on branch 1.2.x (feat(model): support batch key in condscvi)
  docs/release_notes/index.md
  scvi/model/_condscvi.py
  scvi/module/_vaec.py
  tests/model/test_condscvi.py
Labels: on-merge: backport to 1.2.x

#2637 chore(external): remove velovi preprocess functions
  pyproject.toml
  scvi/external/velovi/__init__.py
  scvi/external/velovi/_utils.py
  tests/external/velovi/test_velovi.py
Labels: on-merge: backport to 1.2.x

#2638 Backport PR #2637 on branch 1.2.x (chore(external): remove velovi preprocess functions)
  pyproject.toml
  scvi/external/velovi/__init__.py
  scvi/external/velovi/_utils.py
  tests/external/velovi/test_velovi.py
Labels: on-merge: backport to 1.2.x
