Repository scverse/scvi-tools, pull requests merged in 2024-08, with the labels that each got.

#2924 persistent_workers SCVI
  CHANGELOG.md
  src/scvi/_settings.py
  src/scvi/dataloaders/_ann_dataloader.py
  src/scvi/model/base/_base_model.py
  tests/model/test_scvi.py
Labels: hub, P0

#2929 fix(train) enable drop last option
  CHANGELOG.md
  src/scvi/dataloaders/_data_splitting.py
  src/scvi/external/contrastivevi/_contrastive_data_splitting.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.2.x

#2940 Added PoissonVI Region Factors
  CHANGELOG.md
  src/scvi/external/poissonvi/_model.py
  tests/external/poissonvi/test_poissonvi.py
Labels: on-merge: backport to 1.2.x

#2938 Error in scanvi_ref multiclass accuracy calculation
  CHANGELOG.md
  src/scvi/train/_trainingplans.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2943 Backport PR #2938 on branch 1.2.x (Error in scanvi_ref multiclass accuracy calculation)
  CHANGELOG.md
  src/scvi/train/_trainingplans.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2948 added the future annotations import for many models functions
  src/scvi/model/_amortizedlda.py
  src/scvi/model/_autozi.py
  src/scvi/model/_jaxscvi.py
  src/scvi/model/_linear_scvi.py
Labels: on-merge: backport to 1.2.x

#2950 Backport PR #2948 on branch 1.2.x (added the future annotations import for many models functions)
  src/scvi/model/_amortizedlda.py
  src/scvi/model/_autozi.py
  src/scvi/model/_jaxscvi.py
  src/scvi/model/_linear_scvi.py
Labels: on-merge: backport to 1.2.x

#2951 fix(model) check duplicated gene in celltype marker table
  CHANGELOG.md
  pyproject.toml
  src/scvi/external/cellassign/_model.py
  tests/external/cellassign/test_model_cellassign.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x, P0

#2954 Backport PR #2951 on branch 1.2.x (fix(model) check duplicated gene in celltype marker table)
  CHANGELOG.md
  pyproject.toml
  src/scvi/external/cellassign/_model.py
  tests/external/cellassign/test_model_cellassign.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x, P0
