Repository scverse/scvi-tools, pull requests merged in 2024-07, with the labels that each got.

#2903 ci: change cuda test to ghcr image
  .github/workflows/test_linux_cuda.yml
Labels: cuda tests

#2902 feat(dataloaders): add argument for custom data split indexes
  CHANGELOG.md
  src/scvi/dataloaders/_data_splitting.py
  src/scvi/external/contrastivevi/_contrastive_data_splitting.py
  src/scvi/external/velovi/_model.py
  src/scvi/model/_totalvi.py
  src/scvi/model/base/_pyromixin.py
  src/scvi/module/_utils.py
  tests/dataloaders/test_datasplitter.py
  tests/external/contrastivevi/test_contrastive_datasplitter.py
  tests/model/test_amortizedlda.py
  tests/model/test_scanvi.py
  tests/model/test_scvi.py
Labels: good first issue

#2910 test(model) fixes errors in testing closeness on GPU
  tests/model/test_models_with_minified_data.py
  tests/model/test_pyro.py
Labels: cuda tests

#2913 fix(module) TotalVI fix activation background
  CHANGELOG.md
  src/scvi/module/_totalvae.py
  src/scvi/nn/_base_components.py
  src/scvi/nn/_utils.py
  tests/model/test_pyro.py
  tests/model/test_totalvi.py
  tests/test_data/exp_activation_totalvi/adata.h5ad
  tests/test_data/exp_activation_totalvi/model.pt
Labels: on-merge: backport to 1.2.x

#2916 feat(dataloaders) Issue warning if last batch to small.
  CHANGELOG.md
  src/scvi/dataloaders/_data_splitting.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.2.x

#2915 fix(model) get_normalized_expression support
  CHANGELOG.md
  src/scvi/distributions/__init__.py
  src/scvi/distributions/_negative_binomial.py
  src/scvi/distributions/_normal.py
  src/scvi/model/base/_rnamixin.py
  src/scvi/module/_vae.py
  src/scvi/module/_vaec.py
  tests/model/test_condscvi.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.2.x

#2867 fix(module): address shape mismatch for scanvae loss n_samples
  CHANGELOG.md
  src/scvi/module/_scanvae.py
  src/scvi/module/_utils.py
  tests/module/test_scanvae.py
Labels: on-merge: backport to 1.2.x

#2920 Backport PR #2867 on branch 1.2.x (fix(module): address shape mismatch for scanvae loss n_samples)
  CHANGELOG.md
  src/scvi/module/_scanvae.py
  src/scvi/module/_utils.py
  tests/module/test_scanvae.py
Labels: on-merge: backport to 1.2.x

#2919 Backport PR #2915 on branch 1.2.x (fix(model) get_normalized_expression support)
  CHANGELOG.md
  src/scvi/distributions/__init__.py
  src/scvi/distributions/_negative_binomial.py
  src/scvi/distributions/_normal.py
  src/scvi/model/base/_rnamixin.py
  src/scvi/module/_vae.py
  src/scvi/module/_vaec.py
  tests/model/test_condscvi.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.2.x

#2362 Fixes error in get losses functions
  CHANGELOG.md
  src/scvi/external/scar/_module.py
  src/scvi/model/base/_log_likelihood.py
  src/scvi/model/base/_vaemixin.py
  src/scvi/module/_autozivae.py
  src/scvi/module/_scanvae.py
  src/scvi/module/_totalvae.py
  src/scvi/module/_vae.py
  tests/model/test_scanvi.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.2.x

#2921 Backport PR #2362 on branch 1.2.x (Fixes error in get losses functions)
  CHANGELOG.md
  src/scvi/external/scar/_module.py
  src/scvi/model/base/_log_likelihood.py
  src/scvi/model/base/_vaemixin.py
  src/scvi/module/_autozivae.py
  src/scvi/module/_scanvae.py
  src/scvi/module/_totalvae.py
  src/scvi/module/_vae.py
  tests/model/test_scanvi.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.2.x

#2922 Backport PR #2905 on branch 1.2.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.2.x
