Repository scverse/scvi-tools, pull requests merged in 2024-10, with the labels that each got.

#3004 Backport PR #3003 on branch 1.2.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.2.x

#3009 Backport PR #3007 on branch 1.2.x (Change outlier detection for MRVI to ball admissibility calculation)
  CHANGELOG.md
  src/scvi/external/mrvi/_model.py
Labels: on-merge: backport to 1.2.x

#2834 feat(external): implement METHLYVI for scBS-seq data
  CHANGELOG.md
  docs/api/developer.md
  docs/api/user.md
  docs/references.bib
  docs/user_guide/index.md
  docs/user_guide/models/methylvi.md
  src/scvi/external/__init__.py
  src/scvi/external/methylvi/__init__.py
  src/scvi/external/methylvi/_base_components.py
  src/scvi/external/methylvi/_constants.py
  src/scvi/external/methylvi/_model.py
  src/scvi/external/methylvi/_module.py
  src/scvi/external/methylvi/_utils.py
  tests/external/methylvi/test_methylvi.py
Labels: cuda tests

#3012 Backport PR #3010 on branch 1.3.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.2.x, on-merge: backport to 1.3.x

#3011 Backport PR #3010 on branch 1.2.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.2.x, on-merge: backport to 1.3.x

#3016 Backport PR #3014 on branch 1.2.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.2.x

#3024 (ci) (test) Updated CUDA test yaml file
  .github/workflows/test_linux_cuda.yml
  src/scvi/external/poissonvi/_model.py
  tests/model/test_pyro.py
Labels: cuda tests, on-merge: backport to 1.2.x

#3025 Backport PR #3024 on branch 1.2.x ((ci) (test) Updated CUDA test yaml file)
  .github/workflows/test_linux_cuda.yml
  src/scvi/external/poissonvi/_model.py
  tests/model/test_pyro.py
Labels: cuda tests, on-merge: backport to 1.2.x

#3027 Backport PR #3026 on branch 1.2.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.2.x

#3034 Backport PR #3033 on branch 1.2.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.2.x
