Repository scverse/scvi-tools, pull requests merged in 2024-05, with the labels that each got.

#2765 docs: update contributing guide
  docs/developer/code.md
Labels: on-merge: backport to 1.2.x

#2766 Backport PR #2765 on branch 1.2.x (docs: update contributing guide)
  docs/developer/code.md
Labels: on-merge: backport to 1.2.x

#2769 feat(model): save mudata var names per modality
  CHANGELOG.md
  src/scvi/model/base/_base_model.py
  src/scvi/model/base/_save_load.py
  tests/model/test_totalvi.py
Labels: on-merge: backport to 1.2.x

#2783 build: upperbound on torchmetrics
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#2786 Backport PR #2783 on branch 1.2.x (build: upperbound on torchmetrics)
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#2756 feat(external): add mrvi
  CHANGELOG.md
  docs/api/developer.md
  docs/api/user.md
  docs/references.bib
  docs/tutorials/index_scrna.md
  docs/user_guide/index.md
  docs/user_guide/models/figures/mrvi_graphical_model.svg
  docs/user_guide/models/mrvi.md
  src/scvi/_constants.py
  src/scvi/external/__init__.py
  src/scvi/external/mrvi/__init__.py
  src/scvi/external/mrvi/_components.py
  src/scvi/external/mrvi/_model.py
  src/scvi/external/mrvi/_module.py
  src/scvi/external/mrvi/_types.py
  src/scvi/external/mrvi/_utils.py
  src/scvi/utils/_docstrings.py
  tests/external/mrvi/test_components.py
  tests/external/mrvi/test_model.py
Labels: cuda tests, on-merge: backport to 1.2.x

#2791 Backport PR #2756 on branch 1.2.x (feat(external): add mrvi)
  CHANGELOG.md
  docs/api/developer.md
  docs/api/user.md
  docs/references.bib
  docs/tutorials/index_scrna.md
  docs/user_guide/index.md
  docs/user_guide/models/figures/mrvi_graphical_model.svg
  docs/user_guide/models/mrvi.md
  src/scvi/_constants.py
  src/scvi/external/__init__.py
  src/scvi/external/mrvi/__init__.py
  src/scvi/external/mrvi/_components.py
  src/scvi/external/mrvi/_model.py
  src/scvi/external/mrvi/_module.py
  src/scvi/external/mrvi/_types.py
  src/scvi/external/mrvi/_utils.py
  src/scvi/utils/_docstrings.py
  tests/external/mrvi/test_components.py
  tests/external/mrvi/test_model.py
Labels: cuda tests, on-merge: backport to 1.2.x

#2787 feat(module): change base module to support jax device removal
  src/scvi/module/base/_base_module.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2794 Backport PR #2787 on branch 1.1.x (feat(module): change base module to support jax device removal)
  scvi/module/base/_base_module.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2795 Backport PR #2787 on branch 1.2.x (feat(module): change base module to support jax device removal)
  src/scvi/module/base/_base_module.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2796 ci: mark mrvi tests as optional
  tests/external/mrvi/test_model.py
Labels: on-merge: backport to 1.2.x

#2797 Backport PR #2796 on branch 1.2.x (ci: mark mrvi tests as optional)
  tests/external/mrvi/test_model.py
Labels: on-merge: backport to 1.2.x

#2798 ci: add pytest-pretty plugin, register custom marks
  .github/workflows/test_linux.yml
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_private.yml
  .github/workflows/test_linux_resolution.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_windows.yml
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#2799 Backport PR #2798 on branch 1.2.x (ci: add pytest-pretty plugin, register custom marks)
  .github/workflows/test_linux.yml
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_private.yml
  .github/workflows/test_linux_resolution.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_windows.yml
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#2780 feat(model): add normal distribution support for scvi
  CHANGELOG.md
  src/scvi/model/_scvi.py
  src/scvi/module/_vae.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.2.x

#2801 Backport PR #2780 on branch 1.2.x (feat(model): add normal distribution support for scvi)
  CHANGELOG.md
  src/scvi/model/_scvi.py
  src/scvi/module/_vae.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.2.x

#2807 build: remove torchmetrics upperbound
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#2812 Backport PR #2809 on branch 1.2.x (docs: add census tutorial to index)
  docs/tutorials/index_hub.md
Labels: on-merge: backport to 1.2.x

#2816 fix(dataloaders): sample without replacement for unlabeled obs
  CHANGELOG.md
  src/scvi/dataloaders/_data_splitting.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2817 Backport PR #2816 on branch 1.2.x (fix(dataloaders): sample without replacement for unlabeled obs)
  CHANGELOG.md
  src/scvi/dataloaders/_data_splitting.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x
