Repository scverse/scvi-tools, pull requests merged in 2024-01, with the labels that each got.

#2361 Can criticism indices
  docs/release_notes/index.md
  scvi/criticism/_ppc.py
  tests/criticism/test_criticism.py
Labels: on-merge: backport to 1.1.x

#2389 Backport PR #2361 on branch 1.1.x (Can criticism indices)
  docs/release_notes/index.md
  scvi/criticism/_ppc.py
  tests/criticism/test_criticism.py
Labels: on-merge: backport to 1.1.x

#2396 Switch from `optax.additive_weight_decay` to `optax.add_decayed_weights`
  docs/release_notes/index.md
  scvi/train/_trainingplans.py
Labels: on-merge: backport to 1.1.x

#2397 Backport PR #2396 on branch 1.1.x (Switch from `optax.additive_weight_decay` to `optax.add_decayed_weights`)
  docs/release_notes/index.md
  scvi/train/_trainingplans.py
Labels: on-merge: backport to 1.1.x

#2395 Fix repr for custom distributions, add optional constraint
  .gitignore
  docs/release_notes/index.md
  scvi/distributions/_constraints.py
  scvi/distributions/_negative_binomial.py
  tests/distributions/test_negative_binomial.py
Labels: on-merge: backport to 1.1.x

#2398 Backport PR #2395 on branch 1.1.x (Fix repr for custom distributions, add optional constraint)
  .gitignore
  docs/release_notes/index.md
  scvi/distributions/_constraints.py
  scvi/distributions/_negative_binomial.py
  tests/distributions/test_negative_binomial.py
Labels: on-merge: backport to 1.1.x

#2401 Backport PR #2400 on branch 1.1.x (Bump version to 1.1.0rc2)
  pyproject.toml
Labels: on-merge: backport to 1.1.x

#2404 Remove pypi token from workflow
  .github/workflows/release.yml
Labels: on-merge: backport to 1.1.x

#2406 Add write permissions to release workflow
  .github/workflows/release.yml
Labels: on-merge: backport to 1.1.x

#2407 Backport PR #2406 on branch 1.1.x (Add write permissions to release workflow)
  .github/workflows/release.yml
Labels: on-merge: backport to 1.1.x

#2408 Copy cookiecutter release workflow
  .editorconfig
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/test_linux_cpu.yml
  .github/workflows/test_linux_cpu_pre.yml
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_macos_cpu.yml
  .github/workflows/test_windows_cpu.yml
  .pre-commit-config.yaml
  codecov.yml
  readthedocs.yml
Labels: on-merge: backport to 1.1.x

#2413 Add workflow for private tests
  .github/workflows/test_linux_private.yml
  tests/conftest.py
Labels: on-merge: backport to 1.1.x

#2414 Backport PR #2413 on branch 1.1.x (Add workflow for private tests)
  .github/workflows/test_linux_private.yml
  tests/conftest.py
Labels: on-merge: backport to 1.1.x

#2378 Add support for S3 in `HubModel`
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_private.yml
  docs/release_notes/index.md
  pyproject.toml
  scvi/hub/_model.py
  tests/conftest.py
  tests/hub/test_hub_model.py
Labels: on-merge: backport to 1.1.x

#2416 Update workflows
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_private.yml
Labels: on-merge: backport to 1.1.x

#2415 Backport PR #2378 on branch 1.1.x (Add support for S3 in `HubModel`)
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_private.yml
  docs/release_notes/index.md
  pyproject.toml
  scvi/hub/_model.py
  tests/conftest.py
  tests/hub/test_hub_model.py
Labels: on-merge: backport to 1.1.x

#2417 Backport PR #2416 on branch 1.1.x (Update workflows)
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_private.yml
Labels: on-merge: backport to 1.1.x

#2422 Add clearer error message to `poisson_gene_selection`
  docs/release_notes/index.md
  scvi/data/_preprocessing.py
  tests/data/test_preprocessing.py
Labels: on-merge: backport to 1.1.x

#2423 Backport PR #2422 on branch 1.1.x (Add clearer error message to `poisson_gene_selection`)
  docs/release_notes/index.md
  scvi/data/_preprocessing.py
  tests/data/test_preprocessing.py
Labels: on-merge: backport to 1.1.x

#2425 Fix hub model test names
  tests/hub/test_hub_model.py
Labels: on-merge: backport to 1.1.x

#2426 Backport PR #2425 on branch 1.1.x (Fix hub model test names)
  tests/hub/test_hub_model.py
Labels: on-merge: backport to 1.1.x

#2435 Upgrade actions to setup-python v5
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/test_linux.yml
  .github/workflows/test_linux_pre.yml
  .github/workflows/test_linux_private.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_windows.yml
Labels: on-merge: backport to 1.1.x

#2436 Backport PR #2435 on branch 1.1.x (Upgrade actions to setup-python v5)
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/test_linux.yml
  .github/workflows/test_linux_pre.yml
  .github/workflows/test_linux_private.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_windows.yml
Labels: on-merge: backport to 1.1.x

#2439 Backport PR #2437 on branch 1.1.x (Switch cuda docker image tag)
  .github/workflows/test_linux_cuda.yml
Labels: on-merge: backport to 1.1.x

#2438 Add label triage to cuda, private test workflows
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_private.yml
Labels: all tests

#2440 Backport PR #2438 on branch 1.1.x (Add label triage to cuda, private test workflows)
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_private.yml
Labels: all tests

#2441 Update workflows
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/test_linux.yml
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_pre.yml
  .github/workflows/test_linux_private.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_windows.yml
Labels: on-merge: backport to 1.1.x, all tests

#2443 Update workflow for pushes
  .github/workflows/build.yml
  .github/workflows/test_linux.yml
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_private.yml
Labels: on-merge: backport to 1.1.x, all tests

#2442 Backport PR #2441 on branch 1.1.x (Update workflows)
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/test_linux.yml
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_pre.yml
  .github/workflows/test_linux_private.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_windows.yml
Labels: on-merge: backport to 1.1.x, all tests

#2444 Change workflow names
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_pre.yml
  .github/workflows/test_linux_private.yml
Labels: on-merge: backport to 1.1.x, all tests, prerelease tests

#2445 Backport PR #2444 on branch 1.1.x (Change workflow names)
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_pre.yml
  .github/workflows/test_linux_private.yml
Labels: on-merge: backport to 1.1.x, all tests, prerelease tests

#2446 Fix reinitialization error in GIMVI
  docs/release_notes/index.md
  scvi/external/gimvi/_model.py
  tests/external/gimvi/test_gimvi.py
Labels: on-merge: backport to 1.1.x, cuda tests

#2447 Backport PR #2446 on branch 1.1.x (Fix reinitialization error in GIMVI)
  docs/release_notes/index.md
  scvi/external/gimvi/_model.py
  tests/external/test_gimvi.py
Labels: on-merge: backport to 1.1.x, cuda tests

#2450 Remove black and flake8 as deps
  pyproject.toml
Labels: on-merge: backport to 1.1.x

#2451 Backport PR #2450 on branch 1.1.x (Remove black and flake8 as deps)
  pyproject.toml
Labels: on-merge: backport to 1.1.x

#2455 Add macos m1 test workflow
  .github/workflows/test_macos_m1.yml
Labels: on-merge: backport to 1.1.x

#2456 Backport PR #2455 on branch 1.1.x (Add macos m1 test workflow)
  .github/workflows/test_macos_m1.yml
Labels: on-merge: backport to 1.1.x

#2457 Remove unused files
  .gitattributes
  setup.py
Labels: on-merge: backport to 1.1.x

#2459 Backport PR #2457 on branch 1.1.x (Remove unused files)
  .gitattributes
  setup.py
Labels: on-merge: backport to 1.1.x

#2458 Update codecov and readthedocs yaml
  codecov.yml
  readthedocs.yml
Labels: on-merge: backport to 1.1.x

#2460 Backport PR #2458 on branch 1.1.x (Update codecov and readthedocs yaml)
  codecov.yml
  readthedocs.yml
Labels: on-merge: backport to 1.1.x
