Repository scverse/scvi-tools, pull requests merged in 2024-04, with the labels that each got.

#2640 fix(model): fix docstring in multivi get_normalized_expression
  scvi/model/_multivi.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2642 Backport PR #2640 on branch 1.1.x (fix(model): fix docstring in multivi get_normalized_expression)
  scvi/model/_multivi.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2643 Backport PR #2640 on branch 1.2.x (fix(model): fix docstring in multivi get_normalized_expression)
  scvi/model/_multivi.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2646 chore(train): remove metrics callback and additional_val_metrics
  docs/release_notes/index.md
  scvi/train/_callbacks.py
  scvi/train/_trainer.py
  scvi/train/_trainrunner.py
  tests/train/test_callbacks.py
Labels: on-merge: backport to 1.2.x

#2647 Backport PR #2646 on branch 1.2.x (chore(train): remove metrics callback and additional_val_metrics)
  docs/release_notes/index.md
  scvi/train/_callbacks.py
  scvi/train/_trainer.py
  scvi/train/_trainrunner.py
  tests/train/test_callbacks.py
Labels: on-merge: backport to 1.2.x

#2649 chore(docs): move release notes to changelog.md
  CHANGELOG.md
  docs/_static/img/anndata_manager_schematic.svg
  docs/_static/img/setup_anndata_before_after.svg
  docs/changelog.md
  docs/index.md
Labels: on-merge: backport to 1.2.x

#2651 chore(misc): remove code of conduct
  CODE_OF_CONDUCT.md
Labels: on-merge: backport to 1.2.x

#2650 Backport PR #2649 on branch 1.2.x (chore(docs): move release notes to changelog.md)
  CHANGELOG.md
  docs/_static/img/anndata_manager_schematic.svg
  docs/_static/img/setup_anndata_before_after.svg
  docs/changelog.md
  docs/index.md
Labels: on-merge: backport to 1.2.x

#2652 Backport PR #2651 on branch 1.2.x (chore(misc): remove code of conduct)
  CODE_OF_CONDUCT.md
Labels: on-merge: backport to 1.2.x

#2653 chore(misc): rename dotfiles, copy over .gitignore
  .codecov.yaml
  .gitignore
  .readthedocs.yaml
Labels: on-merge: backport to 1.2.x

#2655 Backport PR #2653 on branch 1.2.x (chore(misc): rename dotfiles, copy over .gitignore)
  .codecov.yaml
  .gitignore
  .readthedocs.yaml
Labels: on-merge: backport to 1.2.x

#2654 chore(ci): clean up workflow files
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/test_linux.yml
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_pre.yml
  .github/workflows/test_linux_private.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_macos_m1.yml
  .github/workflows/test_windows.yml
Labels: on-merge: backport to 1.1.x, all tests, on-merge: backport to 1.2.x

#2660 chore(ci): remove on push hook from optional test workflows
  .github/workflows/test_linux.yml
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_pre.yml
  .github/workflows/test_linux_private.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_windows.yml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2661 Backport PR #2660 on branch 1.1.x (chore(ci): remove on push hook from optional test workflows)
  .github/workflows/test_linux.yml
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_pre.yml
  .github/workflows/test_linux_private.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_windows.yml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2662 Backport PR #2660 on branch 1.2.x (chore(ci): remove on push hook from optional test workflows)
  .github/workflows/test_linux.yml
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_pre.yml
  .github/workflows/test_linux_private.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_windows.yml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2663 chore(ci): add prerelease flag
  .github/workflows/test_linux_pre.yml
Labels: on-merge: backport to 1.1.x, prerelease tests, on-merge: backport to 1.2.x

#2664 Backport PR #2663 on branch 1.1.x (chore(ci): add prerelease flag)
  .github/workflows/test_linux_pre.yml
Labels: on-merge: backport to 1.1.x, prerelease tests, on-merge: backport to 1.2.x

#2665 Backport PR #2663 on branch 1.2.x (chore(ci): add prerelease flag)
  .github/workflows/test_linux_pre.yml
Labels: on-merge: backport to 1.1.x, prerelease tests, on-merge: backport to 1.2.x

#2666 chore(ci): rename prerelease worflow to resolutions
  .github/workflows/test_linux_resolution.yml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x, resolution tests

#2667 Backport PR #2666 on branch 1.1.x (chore(ci): rename prerelease worflow to resolutions)
  .github/workflows/test_linux_resolution.yml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x, resolution tests

#2668 Backport PR #2666 on branch 1.2.x (chore(ci): rename prerelease worflow to resolutions)
  .github/workflows/test_linux_resolution.yml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x, resolution tests

#2670 Backport PR #2669 on branch 1.2.x (chore(misc): update direct dependencies)
  pyproject.toml
  scvi/criticism/__init__.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2644 chore(module): remove unused code paths in scanvae loss
  CHANGELOG.md
  scvi/model/base/_log_likelihood.py
  scvi/module/_scanvae.py
  scvi/train/_trainingplans.py
Labels: on-merge: backport to 1.2.x

#2671 Backport PR #2644 on branch 1.2.x (chore(module): remove unused code paths in scanvae loss)
  CHANGELOG.md
  scvi/model/base/_log_likelihood.py
  scvi/module/_scanvae.py
  scvi/train/_trainingplans.py
Labels: on-merge: backport to 1.2.x

#2673 chore(train): deprecate savebeststate callback and save_best arg
  CHANGELOG.md
  scvi/model/_multivi.py
  scvi/model/_peakvi.py
  scvi/train/_callbacks.py
Labels: on-merge: backport to 1.2.x

#2672 feat(train): add load_best_on_end argument to save checkpoint
  CHANGELOG.md
  scvi/train/_callbacks.py
  tests/train/test_callbacks.py
Labels: cuda tests, on-merge: backport to 1.2.x

#2674 Backport PR #2673 on branch 1.2.x (chore(train): deprecate savebeststate callback and save_best arg)
  CHANGELOG.md
  scvi/model/_multivi.py
  scvi/model/_peakvi.py
  scvi/train/_callbacks.py
Labels: on-merge: backport to 1.2.x

#2675 Backport PR #2672 on branch 1.2.x (feat(train): add load_best_on_end argument to save checkpoint)
  CHANGELOG.md
  scvi/train/_callbacks.py
  tests/train/test_callbacks.py
Labels: cuda tests, on-merge: backport to 1.2.x

#2676 chore(misc): upper bound lightning to 2.3
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#2678 chore(misc): upper bound lightning to 2.11
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#2679 Backport PR #2678 on branch 1.2.x (chore(misc): upper bound ray to 2.11)
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#2681 chore(misc): update license for 2024
  LICENSE
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2682 Backport PR #2681 on branch 1.1.x (chore(misc): update license for 2024)
  LICENSE
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2683 Backport PR #2681 on branch 1.2.x (chore(misc): update license for 2024)
  LICENSE
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2684 chore(misc): update ruff pre-commit and address fixes
  .pre-commit-config.yaml
  scvi/data/_compat.py
  scvi/data/_utils.py
  scvi/external/contrastivevi/_model.py
  scvi/external/gimvi/_module.py
  scvi/external/scar/_model.py
  scvi/external/scbasset/_model.py
  scvi/external/velovi/_model.py
  scvi/model/_autozi.py
  scvi/model/_condscvi.py
  scvi/model/_linear_scvi.py
  scvi/model/_multivi.py
  scvi/model/_peakvi.py
  scvi/model/_scanvi.py
  scvi/model/_totalvi.py
  scvi/model/base/_log_likelihood.py
  scvi/model/base/_rnamixin.py
  scvi/module/_amortizedlda.py
  scvi/module/_totalvae.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2685 Backport PR #2684 on branch 1.2.x (chore(misc): update ruff pre-commit and address fixes)
  .pre-commit-config.yaml
  scvi/data/_compat.py
  scvi/data/_utils.py
  scvi/external/contrastivevi/_model.py
  scvi/external/gimvi/_module.py
  scvi/external/scar/_model.py
  scvi/external/scbasset/_model.py
  scvi/external/velovi/_model.py
  scvi/model/_autozi.py
  scvi/model/_condscvi.py
  scvi/model/_linear_scvi.py
  scvi/model/_multivi.py
  scvi/model/_peakvi.py
  scvi/model/_scanvi.py
  scvi/model/_totalvi.py
  scvi/model/base/_log_likelihood.py
  scvi/model/base/_rnamixin.py
  scvi/module/_amortizedlda.py
  scvi/module/_totalvae.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2689 fix(external): ensure solo soft predict returns probs
  CHANGELOG.md
  scvi/external/solo/_model.py
  tests/external/solo/test_solo.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2690 Backport PR #2689 on branch 1.1.x (fix(external): ensure solo soft predict returns probs)
  docs/release_notes/index.md
  scvi/external/solo/_model.py
  scvi/module/_vae.py
  tests/external/test_solo.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2697 chore(external): add note and warning for solo predict breaking change
  CHANGELOG.md
  scvi/external/solo/_model.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2699 Backport PR #2697 on branch 1.2.x (chore(external): add note and warning for solo predict breaking change)
  CHANGELOG.md
  scvi/external/solo/_model.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2702 chore(misc): add markdown lint and format
  .markdownlint.yaml
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2703 Backport PR #2702 on branch 1.2.x (chore(misc): add markdown lint and format)
  .markdownlint.yaml
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2704 chore(release): bump version to 1.1.3
  pyproject.toml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2705 Backport PR #2704 on branch 1.1.x (chore(release): bump version to 1.1.3)
  pyproject.toml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2706 Backport PR #2704 on branch 1.2.x (chore(release): bump version to 1.1.3)
  pyproject.toml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2707 chore(misc): update github stars badge
  README.md
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2708 Backport PR #2707 on branch 1.2.x (chore(misc): update github stars badge)
  README.md
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2713 docs: update readme
  README.md
Labels: on-merge: backport to 1.2.x

#2714 Backport PR #2713 on branch 1.2.x (docs: update readme)
  README.md
Labels: on-merge: backport to 1.2.x

#2712 docs: update contributing and developer guides
  README.md
  docs/conf.py
  docs/contributing/index.md
  docs/developer/code.md
  docs/developer/index.md
  docs/developer/maintenance.md
  docs/index.md
Labels: on-merge: backport to 1.2.x

#2715 Backport PR #2712 on branch 1.2.x (docs: update contributing and developer guides)
  README.md
  docs/conf.py
  docs/contributing/index.md
  docs/developer/code.md
  docs/developer/index.md
  docs/developer/maintenance.md
  docs/index.md
Labels: on-merge: backport to 1.2.x

#2692 Add Beta-Binomial distribution for modeling scBS-seq data
  CHANGELOG.md
  docs/api/developer.md
  src/scvi/distributions/__init__.py
  src/scvi/distributions/_beta_binomial.py
  src/scvi/distributions/_constraints.py
  tests/distributions/test_beta_binomial.py
  tests/distributions/test_constraints.py
Labels: on-merge: backport to 1.2.x

#2718 Backport PR #2692 on branch 1.2.x (Add Beta-Binomial distribution for modeling scBS-seq data)
  CHANGELOG.md
  docs/api/developer.md
  src/scvi/distributions/__init__.py
  src/scvi/distributions/_beta_binomial.py
  src/scvi/distributions/_constraints.py
  tests/distributions/test_beta_binomial.py
  tests/distributions/test_constraints.py
Labels: on-merge: backport to 1.2.x

#2636 docs: update installation instructions
  docs/developer/code.md
  docs/installation.md
Labels: on-merge: backport to 1.2.x

#2719 Backport PR #2636 on branch 1.2.x (docs: update installation instructions)
  docs/developer/code.md
  docs/installation.md
Labels: on-merge: backport to 1.2.x

#2721 fix(train): address typo in save checkpoint callback
  src/scvi/train/_callbacks.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2724 docs: remove velovi preprocess from api
  docs/api/user.md
Labels: on-merge: backport to 1.2.x

#2722 Backport PR #2721 on branch 1.1.x (fix(train): address typo in save checkpoint callback)
  scvi/train/_callbacks.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2723 Backport PR #2721 on branch 1.2.x (fix(train): address typo in save checkpoint callback)
  src/scvi/train/_callbacks.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2725 Backport PR #2724 on branch 1.2.x (docs: remove velovi preprocess from api)
  docs/api/user.md
Labels: on-merge: backport to 1.2.x

#2727 build: remove criticism from optional deps
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#2728 Backport PR #2727 on branch 1.2.x (build: remove criticism from optional deps)
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#2731 refactor(model): move base model utils to new files
  CHANGELOG.md
  src/scvi/external/contrastivevi/_model.py
  src/scvi/external/poissonvi/_model.py
  src/scvi/hub/_metadata.py
  src/scvi/model/_multivi.py
  src/scvi/model/_peakvi.py
  src/scvi/model/_totalvi.py
  src/scvi/model/base/_archesmixin.py
  src/scvi/model/base/_base_model.py
  src/scvi/model/base/_de_core.py
  src/scvi/model/base/_rnamixin.py
  src/scvi/model/base/_save_load.py
  src/scvi/train/_callbacks.py
  tests/model/test_differential.py
Labels: on-merge: backport to 1.2.x

#2733 refactor(model): substitute save file names with constants
  src/scvi/model/base/_base_model.py
  src/scvi/model/base/_constants.py
  src/scvi/model/base/_save_load.py
Labels: on-merge: backport to 1.2.x

#2732 Backport PR #2731 on branch 1.2.x (refactor(model): move base model utils to new files)
  CHANGELOG.md
  src/scvi/external/contrastivevi/_model.py
  src/scvi/external/poissonvi/_model.py
  src/scvi/hub/_metadata.py
  src/scvi/model/_multivi.py
  src/scvi/model/_peakvi.py
  src/scvi/model/_totalvi.py
  src/scvi/model/base/_archesmixin.py
  src/scvi/model/base/_base_model.py
  src/scvi/model/base/_de_core.py
  src/scvi/model/base/_rnamixin.py
  src/scvi/model/base/_save_load.py
  src/scvi/train/_callbacks.py
  tests/model/test_differential.py
Labels: on-merge: backport to 1.2.x

#2739 feat(data): add explicit synthetic protein and region var names
  CHANGELOG.md
  src/scvi/data/_built_in_data/_synthetic.py
  src/scvi/data/_datasets.py
  tests/data/test_mudata.py
  tests/external/cellassign/test_model_cellassign.py
  tests/model/test_models_with_minified_data.py
  tests/model/test_scvi.py
  tests/model/test_totalvi.py
Labels: on-merge: backport to 1.2.x

#2741 Backport PR #2739 on branch 1.2.x (feat(data): add explicit synthetic protein and region var names)
  CHANGELOG.md
  src/scvi/data/_built_in_data/_synthetic.py
  src/scvi/data/_datasets.py
  tests/data/test_mudata.py
  tests/external/cellassign/test_model_cellassign.py
  tests/model/test_models_with_minified_data.py
  tests/model/test_scvi.py
  tests/model/test_totalvi.py
Labels: on-merge: backport to 1.2.x

#2745 docs: remove contrastive dataloader and splitter from api ref
  docs/api/developer.md
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2746 Backport PR #2745 on branch 1.1.x (docs: remove contrastive dataloader and splitter from api ref)
  docs/api/developer.md
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2747 Backport PR #2745 on branch 1.2.x (docs: remove contrastive dataloader and splitter from api ref)
  docs/api/developer.md
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2749 refactor: rename data_module to datamodule
  CHANGELOG.md
  src/scvi/autotune/_experiment.py
  src/scvi/model/base/_training_mixin.py
  tests/autotune/test_tune.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.2.x

#2750 Backport PR #2749 on branch 1.2.x (refactor: rename data_module to datamodule)
  CHANGELOG.md
  src/scvi/autotune/_experiment.py
  src/scvi/model/base/_training_mixin.py
  tests/autotune/test_tune.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.2.x

#2748 feat(model): support custom dataloaders in vaemixin
  CHANGELOG.md
  src/scvi/model/base/_log_likelihood.py
  src/scvi/model/base/_vaemixin.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.2.x

#2751 build: remove explicit upperbounds for ray and lightning
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#2752 Backport PR #2748 on branch 1.2.x (feat(model): support custom dataloaders in vaemixin)
  CHANGELOG.md
  src/scvi/model/base/_log_likelihood.py
  src/scvi/model/base/_vaemixin.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.2.x

#2753 Backport PR #2751 on branch 1.2.x (build: remove explicit upperbounds for ray and lightning)
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#2758 ci: run tests on pr to any branch
  .github/workflows/test_linux.yml
Labels: on-merge: backport to 1.2.x

#2759 Backport PR #2758 on branch 1.2.x (ci: run tests on pr to any branch)
  .github/workflows/test_linux.yml
Labels: on-merge: backport to 1.2.x
