Repository scverse/scvi-tools, pull requests merged in 2024-02, with the labels that each got.

#2462 Bump version to 1.1.0
  docs/release_notes/index.md
  pyproject.toml
Labels: on-merge: backport to 1.1.x

#2464 Backport PR #2462 on branch 1.1.x (Bump version to 1.1.0)
  docs/release_notes/index.md
  pyproject.toml
Labels: on-merge: backport to 1.1.x

#2463 Add scANVI fix tutorial to index
  docs/tutorials/index_scrna.md
Labels: on-merge: backport to 1.1.x

#2465 Backport PR #2463 on branch 1.1.x (Add scANVI fix tutorial to index)
  docs/tutorials/index_scrna.md
Labels: on-merge: backport to 1.1.x

#2469 Update to codecov-action v4
  .github/workflows/test_linux.yml
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_pre.yml
  .github/workflows/test_linux_private.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_macos_m1.yml
  .github/workflows/test_windows.yml
Labels: on-merge: backport to 1.1.x

#2470 Backport PR #2469 on branch 1.1.x (Update to codecov-action v4)
  .github/workflows/test_linux.yml
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_pre.yml
  .github/workflows/test_linux_private.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_macos_m1.yml
  .github/workflows/test_windows.yml
Labels: on-merge: backport to 1.1.x

#2478 Add support for Ray 2.8-2.9
  docs/release_notes/index.md
  pyproject.toml
  scvi/autotune/_manager.py
Labels: on-merge: backport to 1.1.x

#2479 Backport PR #2478 on branch 1.1.x (Add support for Ray 2.8-2.9)
  docs/release_notes/index.md
  pyproject.toml
  scvi/autotune/_manager.py
Labels: on-merge: backport to 1.1.x

#2480 Make xarray and sparse optional deps, lazy load criticism
  docs/release_notes/index.md
  pyproject.toml
  scvi/criticism/__init__.py
  scvi/model/base/_rnamixin.py
Labels: on-merge: backport to 1.1.x

#2481 Backport PR #2480 on branch 1.1.x (Make xarray and sparse optional deps, lazy load criticism)
  docs/release_notes/index.md
  pyproject.toml
  scvi/criticism/__init__.py
  scvi/model/base/_rnamixin.py
Labels: on-merge: backport to 1.1.x

#2482 Remove chex dependency
  docs/release_notes/index.md
  pyproject.toml
  scvi/autotune/_manager.py
  scvi/external/tangram/_module.py
  scvi/module/base/_base_module.py
Labels: on-merge: backport to 1.1.x

#2483 Backport PR #2482 on branch 1.1.x (Remove chex dependency)
  docs/release_notes/index.md
  pyproject.toml
  scvi/autotune/_manager.py
  scvi/external/tangram/_module.py
  scvi/module/base/_base_module.py
Labels: on-merge: backport to 1.1.x

#2467 Add API for custom dataloaders in `SCVI`
  docs/api/developer.md
  docs/release_notes/index.md
  scvi/model/__init__.py
  scvi/model/_scvi.py
  scvi/model/_utils.py
  scvi/model/base/_base_model.py
  scvi/model/base/_training_mixin.py
  tests/hub/test_hub_metadata.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.1.x

#2487 Add token to codecov action
  .github/workflows/test_linux.yml
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_pre.yml
  .github/workflows/test_linux_private.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_macos_m1.yml
  .github/workflows/test_windows.yml
Labels: on-merge: backport to 1.1.x

#2488 Backport PR #2487 on branch 1.1.x (Add token to codecov action)
  .github/workflows/test_linux.yml
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_pre.yml
  .github/workflows/test_linux_private.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_macos_m1.yml
  .github/workflows/test_windows.yml
Labels: on-merge: backport to 1.1.x

#2485 Use anndata `CSCDataset` and `CSRDataset` for type checks
  docs/release_notes/index.md
  scvi/data/_anntorchdataset.py
  scvi/data/_utils.py
Labels: on-merge: backport to 1.1.x

#2489 Backport PR #2485 on branch 1.1.x (Use anndata `CSCDataset` and `CSRDataset` for type checks)
  docs/release_notes/index.md
  scvi/data/_anntorchdataset.py
  scvi/data/_utils.py
Labels: on-merge: backport to 1.1.x

#2491 Remove default criticism import
  scvi/__init__.py
Labels: on-merge: backport to 1.1.x

#2492 Backport PR #2491 on branch 1.1.x (Remove default criticism import)
  scvi/__init__.py
Labels: on-merge: backport to 1.1.x

#2494 Make `use_observed_lib_size` arg adjustable in `LDVAE`
  docs/release_notes/index.md
  scvi/module/_vae.py
  tests/model/test_linear_scvi.py
Labels: on-merge: backport to 1.1.x

#2495 Backport PR #2494 on branch 1.1.x (Make `use_observed_lib_size` arg adjustable in `LDVAE`)
  docs/release_notes/index.md
  scvi/module/_vae.py
  tests/model/test_linear_scvi.py
Labels: on-merge: backport to 1.1.x

#2505 Backport PR #2504 on branch 1.1.x (Update ruff pre-commit)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.1.x

#2510 Bump to 1.1.0post1
  pyproject.toml
Labels: on-merge: backport to 1.1.x

#2511 Backport PR #2510 on branch 1.1.x (Bump to 1.1.0post1)
  pyproject.toml
Labels: on-merge: backport to 1.1.x

#2512 Bump to post2 and add date to release
  docs/release_notes/index.md
  pyproject.toml
Labels: on-merge: backport to 1.1.x

#2513 Backport PR #2512 on branch 1.1.x (Bump to post2 and add date to release)
  docs/release_notes/index.md
  pyproject.toml
Labels: on-merge: backport to 1.1.x

#2514 Start 1.1.1 release
  docs/release_notes/index.md
  pyproject.toml
Labels: on-merge: backport to 1.1.x

#2515 Backport PR #2514 on branch 1.1.x (Start 1.1.1 release)
  docs/release_notes/index.md
  pyproject.toml
Labels: on-merge: backport to 1.1.x

#2518 Add CUDA 12 to CI
  .github/workflows/test_linux_cuda.yml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2519 Backport PR #2518 on branch 1.1.x (Add CUDA 12 to CI)
  .github/workflows/test_linux_cuda.yml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2520 Backport PR #2518 on branch 1.2.x (Add CUDA 12 to CI)
  .github/workflows/test_linux_cuda.yml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2522 Allow for non-default user params in `POISSONVI`
  docs/release_notes/index.md
  scvi/external/poissonvi/_model.py
  tests/external/poissonvi/test_poissonvi.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2524 Backport PR #2522 on branch 1.1.x (Allow for non-default user params in `POISSONVI`)
  docs/release_notes/index.md
  scvi/external/poissonvi/_model.py
  tests/external/test_poissonvi.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2525 Backport PR #2522 on branch 1.2.x (Allow for non-default user params in `POISSONVI`)
  docs/release_notes/index.md
  scvi/external/poissonvi/_model.py
  tests/external/poissonvi/test_poissonvi.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2526 Update release checklist
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2527 Backport PR #2526 on branch 1.1.x (Update release checklist)
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2528 Backport PR #2526 on branch 1.2.x (Update release checklist)
  .github/ISSUE_TEMPLATE/release_checklist.md
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2532 Backport PR #2531 on branch 1.1.x (Address AnnData 0.10 deprecations)
  docs/release_notes/index.md
  scvi/data/_anntorchdataset.py
  scvi/data/_built_in_data/_pbmc.py
  scvi/data/_utils.py
  scvi/external/gimvi/_utils.py
  scvi/model/base/_utils.py
  tests/data/test_anndata.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2533 Backport PR #2531 on branch 1.2.x (Address AnnData 0.10 deprecations)
  docs/release_notes/index.md
  scvi/data/_anntorchdataset.py
  scvi/data/_built_in_data/_pbmc.py
  scvi/data/_utils.py
  scvi/external/gimvi/_utils.py
  scvi/model/base/_utils.py
  tests/data/test_anndata.py
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2534 add release date to 1.1.1 release
  docs/release_notes/index.md
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2535 Backport PR #2534 on branch 1.1.x (add release date to 1.1.1 release)
  docs/release_notes/index.md
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2536 Backport PR #2534 on branch 1.2.x (add release date to 1.1.1 release)
  docs/release_notes/index.md
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2539 Backport PR #2538 on branch 1.1.x ([releases] start 1.1.2 release)
  pyproject.toml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2540 Backport PR #2538 on branch 1.2.x ([releases] start 1.1.2 release)
  pyproject.toml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2542 [deprecation] deprecate `data.cellxgene`
  docs/release_notes/index.md
  scvi/data/_datasets.py
Labels: on-merge: backport to 1.2.x

#2544 Backport PR #2542 on branch 1.2.x ([deprecation] deprecate `data.cellxgene`)
  docs/release_notes/index.md
  scvi/data/_datasets.py
Labels: on-merge: backport to 1.2.x

#2553 [ci] remove pre flag from tests
  .github/workflows/test_linux.yml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2554 Backport PR #2553 on branch 1.1.x ([ci] remove pre flag from tests)
  .github/workflows/test_linux.yml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2557 remove `reporter` argument in `ModelTuner`
  docs/release_notes/index.md
  scvi/autotune/_manager.py
  scvi/autotune/_tuner.py
  scvi/autotune/_utils.py
  tests/autotune/test_utils.py
Labels: on-merge: backport to 1.2.x

#2559 [ci] add 1.2.x to test workflows
  .github/workflows/test_linux.yml
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_pre.yml
  .github/workflows/test_linux_private.yml
Labels: on-merge: backport to 1.2.x

#2561 refactor `scvi.autotune` with functional API
  docs/api/developer.md
  docs/api/user.md
  docs/release_notes/index.md
  pyproject.toml
  scvi/_decorators.py
  scvi/_types.py
  scvi/autotune/__init__.py
  scvi/autotune/_defaults.py
  scvi/autotune/_experiment.py
  scvi/autotune/_manager.py
  scvi/autotune/_tune.py
  scvi/autotune/_tuner.py
  scvi/external/contrastivevi/_model.py
  scvi/model/base/_base_model.py
  scvi/model/base/_training_mixin.py
  scvi/module/_amortizedlda.py
  scvi/module/_autozivae.py
  scvi/module/_jaxvae.py
  scvi/module/_mrdeconv.py
  scvi/module/_multivae.py
  scvi/module/_peakvae.py
  scvi/module/_scanvae.py
  scvi/module/_totalvae.py
  scvi/module/_vae.py
  scvi/module/_vaec.py
  scvi/module/base/_base_module.py
  scvi/train/_trainer.py
  scvi/train/_trainingplans.py
  tests/autotune/test_experiment.py
  tests/autotune/test_manager.py
  tests/autotune/test_tune.py
  tests/autotune/test_tuner.py
  tests/autotune/test_types.py
Labels: on-merge: backport to 1.2.x

#2563 Backport PR #2561 on branch 1.2.x (refactor `scvi.autotune` with functional API)
  docs/api/developer.md
  docs/api/user.md
  docs/release_notes/index.md
  pyproject.toml
  scvi/_decorators.py
  scvi/_types.py
  scvi/autotune/__init__.py
  scvi/autotune/_defaults.py
  scvi/autotune/_experiment.py
  scvi/autotune/_manager.py
  scvi/autotune/_tune.py
  scvi/autotune/_tuner.py
  scvi/external/contrastivevi/_model.py
  scvi/model/base/_base_model.py
  scvi/model/base/_training_mixin.py
  scvi/module/_amortizedlda.py
  scvi/module/_autozivae.py
  scvi/module/_jaxvae.py
  scvi/module/_mrdeconv.py
  scvi/module/_multivae.py
  scvi/module/_peakvae.py
  scvi/module/_scanvae.py
  scvi/module/_totalvae.py
  scvi/module/_vae.py
  scvi/module/_vaec.py
  scvi/module/base/_base_module.py
  scvi/train/_trainer.py
  scvi/train/_trainingplans.py
  tests/autotune/test_experiment.py
  tests/autotune/test_manager.py
  tests/autotune/test_tune.py
  tests/autotune/test_tuner.py
  tests/autotune/test_types.py
Labels: on-merge: backport to 1.2.x

#2564 [ci] add 1.2.x to build workflow
  .github/workflows/build.yml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2566 Backport PR #2564 on branch 1.2.x ([ci] add 1.2.x to build workflow)
  .github/workflows/build.yml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2565 Backport PR #2564 on branch 1.1.x ([ci] add 1.2.x to build workflow)
  .github/workflows/build.yml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2570 [ci] switch from pytest-cov to coverage
  pyproject.toml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2571 Backport PR #2570 on branch 1.1.x ([ci] switch from pytest-cov to coverage)
  pyproject.toml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2572 Backport PR #2570 on branch 1.2.x ([ci] switch from pytest-cov to coverage)
  pyproject.toml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2574 [feat] add extendable embedding class
  docs/api/developer.md
  docs/release_notes/index.md
  scvi/nn/__init__.py
  scvi/nn/_embedding.py
  tests/nn/test_embedding.py
Labels: on-merge: backport to 1.2.x

#2575 Backport PR #2574 on branch 1.2.x ([feat] add extendable embedding class)
  docs/api/developer.md
  docs/release_notes/index.md
  scvi/nn/__init__.py
  scvi/nn/_embedding.py
  tests/nn/test_embedding.py
Labels: on-merge: backport to 1.2.x

#2576 [feat] implementation of batch embeddings for `SCVI`
  docs/api/developer.md
  docs/release_notes/index.md
  scvi/model/_scvi.py
  scvi/model/base/__init__.py
  scvi/model/base/_embedding_mixin.py
  scvi/module/_vae.py
  scvi/module/base/__init__.py
  scvi/module/base/_embedding_mixin.py
  scvi/nn/_embedding.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.2.x

#2579 Backport PR #2576 on branch 1.2.x ([feat] implementation of batch embeddings for `SCVI`)
  docs/api/developer.md
  docs/release_notes/index.md
  scvi/model/_scvi.py
  scvi/model/base/__init__.py
  scvi/model/base/_embedding_mixin.py
  scvi/module/_vae.py
  scvi/module/base/__init__.py
  scvi/module/base/_embedding_mixin.py
  scvi/nn/_embedding.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.2.x
