Repository scverse/scvi-tools, pull requests merged in 2024-06, with the labels that each got.

#2822 refactor: remove unused file
  src/scvi/model/_metrics.py
  tests/distributions/test_negative_binomial.py
Labels: on-merge: backport to 1.2.x

#2823 Backport PR #2822 on branch 1.2.x (refactor: remove unused file)
  src/scvi/model/_metrics.py
  tests/distributions/test_negative_binomial.py
Labels: on-merge: backport to 1.2.x

#2824 docs: remove left nav icons
  docs/conf.py
Labels: on-merge: backport to 1.2.x

#2825 Backport PR #2824 on branch 1.2.x (docs: remove left nav icons)
  docs/conf.py
Labels: on-merge: backport to 1.2.x

#2578 Reference mapping with MuData-based models
  CHANGELOG.md
  src/scvi/model/base/_archesmixin.py
  tests/model/test_totalvi.py
Labels: on-merge: backport to 1.2.x

#2827 Backport PR #2578 on branch 1.2.x (Reference mapping with MuData-based models)
  CHANGELOG.md
  src/scvi/model/base/_archesmixin.py
  tests/model/test_totalvi.py
Labels: on-merge: backport to 1.2.x

#2828 fix(external): add save load mrvi tests and fix pickling
  src/scvi/external/mrvi/_model.py
  tests/external/mrvi/test_model.py
Labels: on-merge: backport to 1.2.x

#2829 Backport PR #2828 on branch 1.2.x (fix(external): add save load mrvi tests and fix pickling)
  src/scvi/external/mrvi/_model.py
  tests/external/mrvi/test_model.py
Labels: on-merge: backport to 1.2.x

#2831 feat(autotune): add support for ray 2.24
  src/scvi/autotune/_experiment.py
Labels: on-merge: backport to 1.2.x

#2832 Backport PR #2831 on branch 1.2.x (feat(autotune): add support for ray 2.24)
  src/scvi/autotune/_experiment.py
Labels: on-merge: backport to 1.2.x

#2843 build: upper bound numpy 2.0
  pyproject.toml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2844 Backport PR #2843 on branch 1.2.x (build: upper bound numpy 2.0)
  pyproject.toml
Labels: on-merge: backport to 1.1.x, on-merge: backport to 1.2.x

#2854 feat: add support for scipy 1.14.0
  src/scvi/data/_preprocessing.py
  src/scvi/external/scar/_model.py
Labels: on-merge: backport to 1.1.x

#2855 Backport PR #2854 on branch 1.1.x (feat: add support for scipy 1.14.0)
  scvi/data/_preprocessing.py
  scvi/external/scar/_model.py
Labels: on-merge: backport to 1.1.x

#2861 release: bump version to 1.1.4
  pyproject.toml
Labels: on-merge: backport to 1.1.x

#2862 Backport PR #2861 on branch 1.1.x (release: bump version to 1.1.4)
  pyproject.toml
Labels: on-merge: backport to 1.1.x

#2863 docs: add release entry for 1.1.4
  CHANGELOG.md
Labels: on-merge: backport to 1.1.x

#2870 feat(external): add return_logits to solo predict for reproducibility
  CHANGELOG.md
  src/scvi/external/solo/_model.py
  tests/external/solo/test_solo.py
Labels: on-merge: backport to 1.1.x

#2872 release: add date for 1.1.4
  CHANGELOG.md
Labels: on-merge: backport to 1.1.x

#2877 release: add 1.1.5 release
  CHANGELOG.md
  pyproject.toml
Labels: on-merge: backport to 1.1.x
