Repository scverse/scvi-tools, pull requests merged in 2025-05, with the labels that each got.

#3306 Backport PR #3305 on branch 1.3.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.3.x

#3311 Backport PR #3310 on branch 1.3.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.3.x

#3309 ci: remove Jax version constraint
  CHANGELOG.md
  docs/installation.md
  pyproject.toml
  src/scvi/external/mrvi/_model.py
Labels: on-merge: backport to 1.3.x, optional tests

#3312 Backport PR #3309 on branch 1.3.x (ci: remove Jax version constraint)
  CHANGELOG.md
  docs/installation.md
  pyproject.toml
  src/scvi/external/mrvi/_model.py
Labels: on-merge: backport to 1.3.x, optional tests

#3326 Remove collection.load() from MappedCollectionDataModule
  src/scvi/dataloaders/_custom_dataloders.py
Labels: custom_dataloader, on-merge: backport to 1.3.x

#3276 tutorial index page with filterable list
  docs/_static/css/override.css
  docs/_static/js/custom.js
  docs/conf.py
  docs/extensions/filterlist.py
  docs/tutorials/index.md
  docs/tutorials/index_atac.md
  docs/tutorials/index_dev.md
  docs/tutorials/index_hub.md
  docs/tutorials/index_multimodal.md
  docs/tutorials/index_quick_start.md
  docs/tutorials/index_r.md
  docs/tutorials/index_scbs.md
  docs/tutorials/index_scrna.md
  docs/tutorials/index_spatial.md
  docs/tutorials/index_use_cases.md
Labels: on-merge: backport to 1.3.x

#3328 Ensure that compatible bionty version is installed
  pyproject.toml
Labels: custom_dataloader, on-merge: backport to 1.3.x

#3329 Backport PR #3276 on branch 1.3.x (tutorial index page with filterable list)
  docs/_static/css/override.css
  docs/_static/js/custom.js
  docs/conf.py
  docs/extensions/filterlist.py
  docs/tutorials/index.md
  docs/tutorials/index_atac.md
  docs/tutorials/index_dev.md
  docs/tutorials/index_hub.md
  docs/tutorials/index_multimodal.md
  docs/tutorials/index_quick_start.md
  docs/tutorials/index_r.md
  docs/tutorials/index_scbs.md
  docs/tutorials/index_scrna.md
  docs/tutorials/index_spatial.md
  docs/tutorials/index_use_cases.md
Labels: on-merge: backport to 1.3.x

#3330 Backport PR #3328 on branch 1.3.x (Ensure that compatible bionty version is installed)
  pyproject.toml
Labels: custom_dataloader, on-merge: backport to 1.3.x

#3331 update bug of installation with custom dataloder
  docs/api/developer.md
  docs/api/user.md
  src/scvi/dataloaders/_custom_dataloders.py
Labels: custom_dataloader, on-merge: backport to 1.3.x

#3332 Backport PR #3331 on branch 1.3.x (update bug of installation with custom dataloder)
  docs/api/developer.md
  docs/api/user.md
  src/scvi/dataloaders/_custom_dataloders.py
Labels: custom_dataloader, on-merge: backport to 1.3.x

#3333 docs: update docs use cases with correct installations
  docs/user_guide/use_case/custom_dataloaders.md
  docs/user_guide/use_case/downstream_analysis_tasks.md
  docs/user_guide/use_case/hyper_parameters_tuning.md
  docs/user_guide/use_case/multi_gpu_training.md
Labels: on-merge: backport to 1.3.x

#3334 Backport PR #3333 on branch 1.3.x (docs: update docs use cases with correct installations)
  docs/user_guide/use_case/custom_dataloaders.md
  docs/user_guide/use_case/downstream_analysis_tasks.md
  docs/user_guide/use_case/hyper_parameters_tuning.md
  docs/user_guide/use_case/multi_gpu_training.md
Labels: on-merge: backport to 1.3.x

#3336 add missing descriptions and tags to new tutorials
  docs/extensions/filterlist.py
  docs/tutorials/index.md
  docs/tutorials/index_atac.md
  docs/tutorials/index_dev.md
  docs/tutorials/index_hub.md
  docs/tutorials/index_multimodal.md
  docs/tutorials/index_quick_start.md
  docs/tutorials/index_r.md
  docs/tutorials/index_scbs.md
  docs/tutorials/index_scrna.md
  docs/tutorials/index_spatial.md
  docs/tutorials/index_use_cases.md
Labels: tutorials, on-merge: backport to 1.3.x

#3340 Backport PR #3336 on branch 1.3.x (add missing descriptions and tags to new tutorials)
  docs/extensions/filterlist.py
  docs/tutorials/index.md
  docs/tutorials/index_atac.md
  docs/tutorials/index_dev.md
  docs/tutorials/index_hub.md
  docs/tutorials/index_multimodal.md
  docs/tutorials/index_quick_start.md
  docs/tutorials/index_r.md
  docs/tutorials/index_scbs.md
  docs/tutorials/index_scrna.md
  docs/tutorials/index_spatial.md
  docs/tutorials/index_use_cases.md
Labels: tutorials, on-merge: backport to 1.3.x

#3343 ci: make the tests of macos & windows work
  .github/workflows/test_linux_custom_dataloader.yml
  .github/workflows/test_linux_internet.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_macos_mps.yml
  docs/user_guide/use_case/custom_dataloaders.md
  pyproject.toml
  src/scvi/data/_datasets.py
  tests/conftest.py
  tests/dataloaders/test_custom_dataloader.py
Labels: on-merge: backport to 1.3.x, internet tests, windows tests, macos tests

#3345 Backport PR #3343 on branch 1.3.x (ci: make the tests of macos & windows work)
  .github/workflows/test_linux_custom_dataloader.yml
  .github/workflows/test_linux_internet.yml
  .github/workflows/test_macos.yml
  .github/workflows/test_macos_mps.yml
  docs/user_guide/use_case/custom_dataloaders.md
  pyproject.toml
  src/scvi/data/_datasets.py
  tests/conftest.py
  tests/dataloaders/test_custom_dataloader.py
Labels: on-merge: backport to 1.3.x, internet tests, windows tests, macos tests

#3172 feat: nicheVI release
  CHANGELOG.md
  docs/api/user.md
  docs/tutorials/index_spatial.md
  docs/user_guide/index.md
  docs/user_guide/models/nichevi.md
  src/scvi/external/__init__.py
  src/scvi/external/nichevi/__init__.py
  src/scvi/external/nichevi/_components.py
  src/scvi/external/nichevi/_constants.py
  src/scvi/external/nichevi/_log_likelihood.py
  src/scvi/external/nichevi/_model.py
  src/scvi/external/nichevi/_module.py
  src/scvi/external/nichevi/differential_expression/__init__.py
  src/scvi/external/nichevi/differential_expression/_de_utils.py
  src/scvi/external/nichevi/differential_expression/_marker_classifier.py
  src/scvi/external/nichevi/differential_expression/_niche_de_core.py
  src/scvi/external/nichevi/differential_expression/_results_dataclass.py
  tests/external/nichevi/test_nichevi.py
Labels: on-merge: backport to 1.3.x, draft

#3351 Backport PR #3339 on branch 1.3.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.3.x

#3341 fix: getting protein probabilities in multivi
  src/scvi/model/_multivi.py
  src/scvi/module/_multivae.py
  tests/model/test_multivi.py
  tests/model/test_totalvi.py
Labels: multivi, on-merge: backport to 1.3.x

#3354 Backport PR #3341 on branch 1.3.x (fix: getting protein probabilities in multivi)
  src/scvi/model/_multivi.py
  src/scvi/module/_multivae.py
  tests/model/test_multivi.py
  tests/model/test_totalvi.py
Labels: multivi, on-merge: backport to 1.3.x

#3355 fix: totalanvi_scaraches fix
  .codecov.yaml
  CHANGELOG.md
  pyproject.toml
  src/scvi/train/_trainingplans.py
  tests/dataloaders/test_custom_dataloader.py
  tests/external/totalanvi/test_totalanvi.py
  tests/model/test_scanvi.py
Labels: on-merge: backport to 1.3.x

#3360 fix: change None column to "None" in IG single modality
  src/scvi/model/_multivi.py
  src/scvi/model/base/_training_mixin.py
  tests/model/test_scanvi.py
Labels: on-merge: backport to 1.3.x

#3361 Backport PR #3360 on branch 1.3.x (fix: change None column to "None" in IG single modality)
  src/scvi/model/_multivi.py
  src/scvi/model/base/_training_mixin.py
  tests/model/test_scanvi.py
Labels: on-merge: backport to 1.3.x
