Repository scverse/scvi-tools, pull requests merged in 2025-08, with the labels that each got.

#3446 fix: need to have criticism module in init of scvi-tools
  src/scvi/__init__.py
  tests/criticism/test_criticism.py
Labels: on-merge: backport to 1.3.x

#3452 fix: library_size in totalvi, summary_stats duplicate fields and checkpointing with autotune
  .github/workflows/test_linux_autotune.yml
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_multigpu.yml
  CHANGELOG.md
  docs/installation.md
  src/scvi/autotune/_experiment.py
  src/scvi/autotune/_tune.py
  src/scvi/data/_manager.py
  src/scvi/model/_totalvi.py
  tests/autotune/test_tune.py
  tests/model/test_totalvi.py
Labels: autotune, on-merge: backport to 1.3.x

#3455 Backport PR #3451 on branch 1.3.x (test: Put the slowest unit tests under tags)
  tests/criticism/test_criticism.py
  tests/external/resolvi/test_resolvi.py
  tests/external/scbasset/test_scbasset.py
  tests/external/totalanvi/test_totalanvi.py
  tests/external/velovi/test_velovi.py
  tests/model/test_models_with_minified_data.py
  tests/model/test_scanvi.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.3.x

#3458 Backport PR #3457 on branch 1.3.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.3.x

#3461 Fix: tileDB custom dataloader model with covariates, save and load
  CHANGELOG.md
  docs/user_guide/use_case/custom_dataloaders.md
  src/scvi/dataloaders/_custom_dataloders.py
  src/scvi/model/base/_base_model.py
  src/scvi/module/_vae.py
  tests/dataloaders/test_custom_dataloader.py
Labels: custom_dataloader, on-merge: backport to 1.3.x

#3462 Backport PR #3461 on branch 1.3.x (Fix: tileDB custom dataloader model with covariates, save and load)
  CHANGELOG.md
  docs/user_guide/use_case/custom_dataloaders.md
  src/scvi/dataloaders/_custom_dataloders.py
  src/scvi/model/base/_base_model.py
  src/scvi/module/_vae.py
  tests/dataloaders/test_custom_dataloader.py
Labels: custom_dataloader, on-merge: backport to 1.3.x

#3471 Backport PR #3469 on branch 1.3.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.3.x

#3473 Fix: update several models' differential_accessibility issues
  CHANGELOG.md
  src/scvi/external/methylvi/_base_components.py
  src/scvi/external/poissonvi/_model.py
  src/scvi/model/_multivi.py
  src/scvi/model/_peakvi.py
  tests/external/methylvi/test_methylvi.py
  tests/external/poissonvi/test_poissonvi.py
  tests/model/test_autozi.py
  tests/model/test_multivi.py
  tests/model/test_peakvi.py
Labels: on-merge: backport to 1.3.x

#3476 Backport PR #3474 on branch 1.3.x (docs: change location of mrvi,tahoe100,custom_dl new tutorials)
  docs/tutorials/index.md
  docs/tutorials/index_custom_dl.md
  docs/tutorials/index_hub.md
  docs/tutorials/index_scrna.md
  docs/tutorials/index_use_cases.md
  docs/user_guide/use_case/custom_dataloaders.md
Labels: on-merge: backport to 1.3.x

#3477 feat: Fix scarches surgery in SysVI
  CHANGELOG.md
  src/scvi/external/sysvi/_model.py
  src/scvi/model/base/_archesmixin.py
  tests/external/sysvi/test_sysvi.py
Labels: on-merge: backport to 1.3.x

#3479 Backport PR #3477 on branch 1.3.x (feat: Fix scarches surgery in SysVI)
  CHANGELOG.md
  src/scvi/external/sysvi/_model.py
  src/scvi/model/base/_archesmixin.py
  tests/external/sysvi/test_sysvi.py
Labels: on-merge: backport to 1.3.x

#3443 feat: Downstream Analysis functions multi GPU support
  CHANGELOG.md
  src/scvi/model/base/_rnamixin.py
  src/scvi/model/base/_vaemixin.py
  tests/model/test_multigpu.py
Labels: on-merge: backport to 1.3.x, multiGPU tests

#3481 Backport PR #3443 on branch 1.3.x (feat: Downstream Analysis functions multi GPU support)
  CHANGELOG.md
  src/scvi/model/base/_rnamixin.py
  src/scvi/model/base/_vaemixin.py
  tests/model/test_multigpu.py
Labels: on-merge: backport to 1.3.x, multiGPU tests
