Repository scverse/scvi-tools, pull requests merged in 2025-09, with the labels that each got.

#3486 docs: Updated models internal links
  CHANGELOG.md
  docs/user_guide/models/multivi.md
  docs/user_guide/models/totalanvi.md
  src/scvi/autotune/_experiment.py
  src/scvi/autotune/_tune.py
  src/scvi/criticism/_ppc.py
  src/scvi/data/_built_in_data/_heartcellatlas.py
  src/scvi/data/_datasets.py
  src/scvi/data/_manager.py
  src/scvi/data/fields/_arraylike_field.py
  src/scvi/data/fields/_dataframe_field.py
  src/scvi/data/fields/_layer_field.py
  src/scvi/data/fields/_mudata.py
  src/scvi/data/fields/_uns_field.py
  src/scvi/dataloaders/_data_splitting.py
  src/scvi/external/contrastivevi/_contrastive_data_splitting.py
  src/scvi/external/contrastivevi/_model.py
  src/scvi/external/cytovi/_model.py
  src/scvi/external/decipher/_model.py
  src/scvi/external/methylvi/__init__.py
  src/scvi/external/methylvi/_base_components.py
  src/scvi/external/methylvi/_methylanvi_model.py
  src/scvi/external/poissonvi/_model.py
  src/scvi/external/resolvi/_model.py
  src/scvi/external/resolvi/_utils.py
  src/scvi/external/scar/_model.py
  src/scvi/external/scviva/_model.py
  src/scvi/external/stereoscope/_model.py
  src/scvi/external/sysvi/_base_components.py
  src/scvi/external/sysvi/_module.py
  src/scvi/external/totalanvi/_model.py
  src/scvi/external/velovi/_model.py
  src/scvi/hub/_metadata.py
  src/scvi/model/_condscvi.py
  src/scvi/model/_destvi.py
  src/scvi/model/_multivi.py
  src/scvi/model/_scanvi.py
  src/scvi/model/_scvi.py
  src/scvi/model/_totalvi.py
  src/scvi/model/base/_base_model.py
  src/scvi/model/base/_rnamixin.py
  src/scvi/module/_vae.py
  src/scvi/nn/_base_components.py
  src/scvi/train/_trainingplans.py
  tests/model/test_multivi.py
Labels: on-merge: backport to 1.3.x

#3505 Backport PR #3504 on branch 1.3.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.3.x

#3510 test: update test files with py313 pre stage
  .github/workflows/build.yml
  .github/workflows/build_image_base.yaml
  .github/workflows/build_image_latest.yaml
  .github/workflows/release.yml
  .github/workflows/test_linux_custom_dataloader.yml
  .github/workflows/test_linux_internet.yml
  .github/workflows/test_linux_optional.yml
  .github/workflows/test_linux_private.yml
  docs/installation.md
Labels: on-merge: backport to 1.3.x

#3513 Backport PR #3501 on branch 1.3.x (feat: add a checkpoint to trainer fit)
  CHANGELOG.md
  src/scvi/train/_trainrunner.py
  tests/train/test_callbacks.py
Labels: on-merge: backport to 1.3.x

#3506 tests: change the tests to be on py3.13 by default
  .github/workflows/release.yml
  .github/workflows/test_linux_autotune.yml
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_multigpu.yml
  pyproject.toml
  src/scvi/hub/_url.py
  tests/dataloaders/test_custom_dataloader.py
Labels: autotune, hub, cuda tests, private tests, custom_dataloader, on-merge: backport to 1.3.x, optional tests, internet tests, cuda optional tests

#3524 feat: expose solver paramter to becnhmarker during autotune
  CHANGELOG.md
  docs/references.bib
  src/scvi/autotune/_experiment.py
  src/scvi/autotune/_tune.py
  tests/autotune/test_tune.py
Labels: on-merge: backport to 1.3.x

#3543 Fix in non multiGPU training to have history saved in memory, and not on disk by default
  CHANGELOG.md
  src/scvi/external/mrvi_jax/_model.py
  src/scvi/train/_logger.py
  src/scvi/train/_trainer.py
  tests/dataloaders/test_dataloaders.py
  tests/external/mrvi_jax/test_jaxmrvi_model.py
  tests/model/test_multigpu.py
  tests/model/test_scvi.py
Labels: cuda tests, on-merge: backport to 1.4.x

#3544 Backport PR #3543 on branch 1.4.x (Fix in non multiGPU training to have history saved in memory, and not on disk by default)
  CHANGELOG.md
  src/scvi/external/mrvi_jax/_model.py
  src/scvi/train/_logger.py
  src/scvi/train/_trainer.py
  tests/dataloaders/test_dataloaders.py
  tests/external/mrvi_jax/test_jaxmrvi_model.py
  tests/model/test_multigpu.py
  tests/model/test_scvi.py
Labels: cuda tests, on-merge: backport to 1.4.x

#3547 Backport PR #3538 on branch 1.4.x (fix: UnboundLocalError for sliced_data in AnnTorchDataset.__getitem__)
  src/scvi/data/_anntorchdataset.py
  src/scvi/external/mrvi_jax/_model.py
Labels: custom_dataloader, optional tests, on-merge: backport to 1.4.x
