Repository scverse/scvi-tools, pull requests merged in 2025-04, with the labels that each got.

#3277 feat: extra_payload_autotune flag
  .github/workflows/test_linux_internet.yml
  src/scvi/autotune/_experiment.py
  src/scvi/module/_scanvae.py
  src/scvi/module/_vae.py
  src/scvi/train/_trainingplans.py
  tests/autotune/test_tune.py
Labels: autotune, on-merge: backport to 1.3.x

#3279 Backport PR #3277 on branch 1.3.x (feat: extra_payload_autotune flag)
  .github/workflows/test_linux_internet.yml
  src/scvi/autotune/_experiment.py
  src/scvi/module/_scanvae.py
  src/scvi/module/_vae.py
  src/scvi/train/_trainingplans.py
  tests/autotune/test_tune.py
Labels: autotune, on-merge: backport to 1.3.x

#3280 fix: changed the tqdm to track with a silent option in all models
  src/scvi/external/contrastivevi/_model.py
  src/scvi/external/resolvi/_utils.py
  src/scvi/model/_multivi.py
  src/scvi/model/_totalvi.py
  src/scvi/model/base/_rnamixin.py
Labels: on-merge: backport to 1.3.x

#3281 Backport PR #3280 on branch 1.3.x (fix: changed the tqdm to track with a silent option in all models)
  src/scvi/external/contrastivevi/_model.py
  src/scvi/external/resolvi/_utils.py
  src/scvi/model/_multivi.py
  src/scvi/model/_totalvi.py
  src/scvi/model/base/_rnamixin.py
Labels: on-merge: backport to 1.3.x

#3284 fix: bring back cellxgene-census to pyproject under tag "file_sharing"
  pyproject.toml
Labels: on-merge: backport to 1.3.x, internet tests

#3288 Backport PR #3286 on branch 1.3.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.3.x

#3291 Backport PR #3290 on branch 1.3.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.3.x

#3293 Backport PR #3292 on branch 1.3.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.3.x

#3297 fix: removed verbose from ReduceLROnPlateau to meet new torch version needs
  src/scvi/train/_trainingplans.py
Labels: on-merge: backport to 1.3.x

#3294 feat: Linear SCVI adata minifiction
  CHANGELOG.md
  src/scvi/model/_linear_scvi.py
  tests/model/test_linear_scvi.py
Labels: on-merge: backport to 1.3.x

#3302 Backport PR #3300 on branch 1.3.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.3.x
