Repository scverse/scvi-tools, pull requests merged in 2025-01, with the labels that each got.

#3118 build: move pooch to dependencies decorator
  src/scvi/data/_built_in_data/_dataset_10x.py
  src/scvi/data/_built_in_data/_loom.py
  src/scvi/data/_built_in_data/_smfish.py
Labels: on-merge: backport to 1.2.x, internet tests

#3119 Backport PR #3118 on branch 1.2.x (build: move pooch to dependencies decorator)
  src/scvi/data/_built_in_data/_dataset_10x.py
  src/scvi/data/_built_in_data/_loom.py
  src/scvi/data/_built_in_data/_smfish.py
Labels: on-merge: backport to 1.2.x, internet tests

#3124 Backport PR #3122 on branch 1.2.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.2.x, on-merge: backport to 1.3.x

#3126 misc: Fix the batch size warning in case of small last batch when using external indices
  src/scvi/dataloaders/_data_splitting.py
Labels: on-merge: backport to 1.2.x

#3127 Backport PR #3126 on branch 1.2.x (misc: Fix the batch size warning in case of small last batch when using external indices)
  src/scvi/dataloaders/_data_splitting.py
Labels: on-merge: backport to 1.2.x

#3128 bug: Batch Size is not utilised properly with the use of external indices following last batch fix.
  CHANGELOG.md
  src/scvi/dataloaders/_data_splitting.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.2.x

#3140 Backport PR #3132 on branch 1.2.x (feat: Improve speed for transfer fields if using many categories.)
  src/scvi/data/fields/_dataframe_field.py
Labels: on-merge: backport to 1.2.x

#3147 docs: update RTD for docker links
  docs/developer/maintenance.md
  docs/installation.md
Labels: on-merge: backport to 1.2.x

#3148 Backport PR #3147 on branch 1.2.x (docs: update RTD for docker links)
  docs/developer/maintenance.md
  docs/installation.md
Labels: on-merge: backport to 1.2.x

#3149 Backport PR #3143 on branch 1.2.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
  docs/extensions/typed_returns.py
  src/scvi/data/_utils.py
  src/scvi/external/cellassign/_model.py
  src/scvi/external/contrastivevi/_model.py
  src/scvi/model/_multivi.py
  src/scvi/model/base/_archesmixin.py
  src/scvi/module/base/_base_module.py
  src/scvi/train/_callbacks.py
Labels: on-merge: backport to 1.2.x

#3150 test: fix the genomepy bug
  tests/data/test_preprocessing.py
Labels: on-merge: backport to 1.2.x

#3151 Backport PR #3150 on branch 1.2.x (test: fix the genomepy bug)
  tests/data/test_preprocessing.py
Labels: on-merge: backport to 1.2.x

#3152 docs: update totlavi tutorial with additional pre filtering information
  src/scvi/data/_download.py
Labels: on-merge: backport to 1.2.x

#3153 Backport PR #3152 on branch 1.2.x (docs: update totlavi tutorial with additional pre filtering information)
  src/scvi/data/_download.py
Labels: on-merge: backport to 1.2.x

#3158 Backport PR #3157 on branch 1.2.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.2.x

#3144 (feat) Release resolVI
  CHANGELOG.md
  docs/api/developer.md
  docs/api/user.md
  docs/references.bib
  docs/tutorials/index_spatial.md
  docs/user_guide/index.md
  docs/user_guide/models/resolvi.md
  src/scvi/external/__init__.py
  src/scvi/external/resolvi/__init__.py
  src/scvi/external/resolvi/_model.py
  src/scvi/external/resolvi/_module.py
  src/scvi/external/resolvi/_utils.py
  src/scvi/model/_multivi.py
  src/scvi/model/_peakvi.py
  src/scvi/model/_totalvi.py
  src/scvi/model/base/_archesmixin.py
  src/scvi/model/base/_base_model.py
  src/scvi/model/base/_de_core.py
  src/scvi/model/base/_differential.py
  src/scvi/model/base/_pyromixin.py
  src/scvi/model/base/_rnamixin.py
  src/scvi/module/_scanvae.py
  src/scvi/module/_totalvae.py
  src/scvi/module/base/_base_module.py
  src/scvi/train/_callbacks.py
  src/scvi/train/_trainingplans.py
  src/scvi/utils/_docstrings.py
  tests/external/resolvi/test_resolvi.py
  tests/model/test_differential.py
  tests/model/test_pyro.py
  tests/model/test_scvi.py
Labels: on-merge: backport to 1.3.x

#3161 ci: ray_tune version update
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#3162 Backport PR #3161 on branch 1.2.x (ci: ray_tune version update)
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#3167 Backport PR #3165 on branch 1.2.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.2.x
