Repository scverse/scvi-tools, pull requests merged in 2025-02, with the labels that each got.

#3174 Backport PR #3173 on branch 1.2.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.2.x

#3182 Backport PR #3181 on branch 1.2.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.2.x

#3184 ci: upper bound jax version due to mrvi slowdown
  pyproject.toml
Labels: on-merge: backport to 1.2.x

#3190 test: fixed several tests full path to load and save models
  tests/model/exp_activation_totalvi_re/adata.h5ad
  tests/model/exp_activation_totalvi_re/model.pt
  tests/model/pre_logits_fix_scanvi/adata.h5ad
  tests/model/pre_logits_fix_scanvi/model.pt
  tests/model/saved_model/model.pt
  tests/model/test_condscvi/adata.h5ad
  tests/model/test_condscvi/model.pt
  tests/model/test_scanvi.py
Labels: on-merge: backport to 1.2.x

#3191 Backport PR #3190 on branch 1.2.x (test: fixed several tests full path to load and save models)
  tests/model/exp_activation_totalvi_re/adata.h5ad
  tests/model/exp_activation_totalvi_re/model.pt
  tests/model/pre_logits_fix_scanvi/adata.h5ad
  tests/model/pre_logits_fix_scanvi/model.pt
  tests/model/saved_model/model.pt
  tests/model/test_condscvi/adata.h5ad
  tests/model/test_condscvi/model.pt
  tests/model/test_scanvi.py
Labels: on-merge: backport to 1.2.x

#3121 feat: add get_normalized_expression to more models
  CHANGELOG.md
  src/scvi/external/cellassign/_model.py
  src/scvi/external/cellassign/_module.py
  src/scvi/external/gimvi/_model.py
  src/scvi/external/gimvi/_module.py
  src/scvi/external/poissonvi/_model.py
  src/scvi/model/_autozi.py
  src/scvi/model/_condscvi.py
  src/scvi/model/_destvi.py
  src/scvi/model/_peakvi.py
  src/scvi/model/base/_rnamixin.py
  src/scvi/module/_autozivae.py
  src/scvi/module/_mrdeconv.py
  src/scvi/module/_peakvae.py
  src/scvi/module/_vaec.py
  src/scvi/nn/_base_components.py
  tests/external/cellassign/test_model_cellassign.py
  tests/external/gimvi/test_gimvi.py
  tests/external/poissonvi/test_poissonvi.py
  tests/model/test_autozi.py
  tests/model/test_condscvi.py
  tests/model/test_destvi.py
  tests/model/test_peakvi.py
  tests/test_data/condscvi_pre_batch/model.pt
Labels: on-merge: backport to 1.2.x

#3159 fix: nan failure during training
  CHANGELOG.md
  src/scvi/train/_callbacks.py
  tests/train/test_callbacks.py
Labels: on-merge: backport to 1.2.x

#3195 feat: SysVI for cycle consistency loss and VampPrior.
  src/scvi/external/__init__.py
  src/scvi/external/sysvi/__init__.py
  src/scvi/external/sysvi/_base_components.py
  src/scvi/external/sysvi/_model.py
  src/scvi/external/sysvi/_module.py
  src/scvi/external/sysvi/_priors.py
  src/scvi/nn/_base_components.py
  tests/external/sysvi/test_sysvi.py
Labels: on-merge: backport to 1.3.x

#3189 fix: MrVI MixtureSameFamily log probability fixed
  src/scvi/external/mrvi/_model.py
  src/scvi/external/mrvi/_module.py
  tests/external/mrvi/test_model.py
Labels: on-merge: backport to 1.2.x, optional tests

#3202 Backport PR #3189 on branch 1.2.x (fix: MrVI MixtureSameFamily log probability fixed)
  src/scvi/external/mrvi/_model.py
  src/scvi/external/mrvi/_module.py
  tests/external/mrvi/test_model.py
Labels: on-merge: backport to 1.2.x, optional tests

#3207 Backport PR #3206 on branch 1.2.x ([pre-commit.ci] pre-commit autoupdate)
  .pre-commit-config.yaml
Labels: on-merge: backport to 1.2.x

#3204 docs: SysVI docs
  CHANGELOG.md
  docs/api/developer.md
  docs/api/user.md
  docs/references.bib
  docs/tutorials/index_scrna.md
  docs/user_guide/index.md
  docs/user_guide/models/sysvi.md
Labels: on-merge: backport to 1.3.x

#3212 Backport PR #3204 on branch 1.3.x (docs: SysVI docs)
  CHANGELOG.md
  docs/api/developer.md
  docs/api/user.md
  docs/references.bib
  docs/tutorials/index_scrna.md
  docs/user_guide/index.md
  docs/user_guide/models/sysvi.md
Labels: on-merge: backport to 1.3.x

#3214 docs: general updates to docs and tests
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_multigpu.yml
  docs/user_guide/models/gimvi.md
  docs/user_guide/models/poissonvi.md
  docs/user_guide/models/scbasset.md
  docs/user_guide/models/sysvi.md
Labels: on-merge: backport to 1.3.x

#3215 Backport PR #3214 on branch 1.3.x (docs: general updates to docs and tests)
  .github/workflows/test_linux_cuda.yml
  .github/workflows/test_linux_multigpu.yml
  docs/user_guide/models/gimvi.md
  docs/user_guide/models/poissonvi.md
  docs/user_guide/models/scbasset.md
  docs/user_guide/models/sysvi.md
Labels: on-merge: backport to 1.3.x

#3193 Support of dask arrays in AnnTorchDataset.
  CHANGELOG.md
  pyproject.toml
  src/scvi/data/_anntorchdataset.py
  src/scvi/data/_utils.py
  src/scvi/utils/__init__.py
  src/scvi/utils/_dependencies.py
  tests/data/test_anndata.py
Labels: on-merge: backport to 1.3.x

#3203 feat: Add generic support for Vamp and MoG prior
  src/scvi/module/base/__init__.py
  src/scvi/module/base/_priors.py
Labels: on-merge: backport to 1.3.x

#3216 Backport PR #3193 on branch 1.3.x (Support of dask arrays in AnnTorchDataset.)
  CHANGELOG.md
  pyproject.toml
  src/scvi/data/_anntorchdataset.py
  src/scvi/data/_utils.py
  src/scvi/utils/__init__.py
  src/scvi/utils/_dependencies.py
  tests/data/test_anndata.py
Labels: on-merge: backport to 1.3.x

#3200 docs: Adding common use cases
  CHANGELOG.md
  docs/_static/img/umap.png
  docs/_static/multigpu.png
  docs/faq.md
  docs/user_guide/index.md
  docs/user_guide/use_case/custom_dataloaders.md
  docs/user_guide/use_case/downstream_analysis_tasks.md
  docs/user_guide/use_case/early_stopping.md
  docs/user_guide/use_case/hyper_parameters_tuning.md
  docs/user_guide/use_case/multi_gpu_training.md
  docs/user_guide/use_case/saving_and_loading_models.md
  docs/user_guide/use_case/using_callbacks.md
  src/scvi/train/_callbacks.py
  src/scvi/train/_trainingplans.py
  tests/train/test_callbacks.py
Labels: on-merge: backport to 1.2.x, on-merge: backport to 1.3.x

#3164 feat: SemiSupervised Training Mixin class
  .github/workflows/test_linux_autotune.yml
  CHANGELOG.md
  docs/tutorials/index.md
  docs/tutorials/index_hub.md
  docs/tutorials/index_tuning.md
  docs/tutorials/index_use_cases.md
  docs/user_guide/use_case/downstream_analysis_tasks.md
  pyproject.toml
  src/scvi/model/_scanvi.py
  src/scvi/model/base/__init__.py
  src/scvi/model/base/_training_mixin.py
  tests/autotune/test_tune.py
  tests/conftest.py
  tests/model/test_scanvi.py
Labels: on-merge: backport to 1.3.x

#3222 Backport PR #3164 on branch 1.3.x (feat: SemiSupervised Training Mixin class)
  .github/workflows/test_linux_autotune.yml
  CHANGELOG.md
  docs/tutorials/index.md
  docs/tutorials/index_hub.md
  docs/tutorials/index_tuning.md
  docs/tutorials/index_use_cases.md
  docs/user_guide/use_case/downstream_analysis_tasks.md
  pyproject.toml
  src/scvi/model/_scanvi.py
  src/scvi/model/base/__init__.py
  src/scvi/model/base/_training_mixin.py
  tests/autotune/test_tune.py
  tests/conftest.py
  tests/model/test_scanvi.py
Labels: on-merge: backport to 1.3.x
